In [192]:

# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,出售截止日,拟出售比例,拟出售数量,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,NaT,0.0,0.0,0.00,0.0,0.00,0.0,0.0,False,祎煜环保
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,NaT,0.0,0.0,0.00,0.0,0.00,0.0,0.0,False,祎煜环保
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,NaT,0.0,0.0,0.00,0.0,0.00,0.0,0.0,False,祎煜环保
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,NaT,0.0,0.0,0.00,0.0,0.00,0.0,0.0,False,祎煜环保
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,NaT,0.0,0.0,0.00,0.0,0.00,0.0,0.0,False,祎煜环保
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,NaT,0.0,0.0,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,NaT,0.0,0.0,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,NaT,0.0,0.0,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,NaT,0.0,0.0,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,NaT,0.0,0.0,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业

In [193]:
df[df['日期']==df['决议通过日']]

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,出售截止日,拟出售比例,拟出售数量,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称
433,2021-10-15,11.687253,4.000000e+07,NaN,True,2021-10-15,2021-10-25,2021-12-24,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,NaT,0.0000,0.00,0.00,0.000000,0.00,0.00,0.0000,False,祎煜环保
610,2022-07-08,12.766299,4.000000e+07,NaN,True,2022-07-08,2022-07-18,2022-11-01,竞价回购,维护公司价值及股东权益所必需,...,NaT,0.0000,0.00,0.00,0.000000,0.00,0.00,0.0000,False,祎煜环保
717,2022-12-13,8.174095,4.000000e+07,NaN,True,2022-12-13,2022-12-23,2023-04-28,要约回购,维护公司价值及股东权益所必需,...,NaT,0.0000,0.00,0.00,0.000000,0.00,0.00,0.0000,False,祎煜环保
951,2023-12-04,9.996633,4.000000e+07,NaN,True,2023-12-04,2023-12-14,2024-02-05,要约回购,股权激励或者员工持股计划,...,NaT,0.0000,0.00,0.00,0.000000,0.00,0.00,0.0000,False,祎煜环保
996,2024-02-13,12.485538,3.009884e+07,NaN,True,2024-02-13,2024-02-23,2024-05-08,竞价回购,股权激励或者员工持股计划,...,2024-04-30,0.0202,789069.40,11.46,0.001360,40928.81,767588.74,0.9728,True,祎煜环保
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59379,2024-07-29,24.289156,2.385951e+07,NaN,True,2024-07-29,2024-08-08,2024-11-01,竞价回购,股权激励或者员工持股计划,...,2024-09-26,0.0030,70691.61,24.12,0.000000,3.22,70689.98,1.0000,True,暄珵医药
59960,2021-12-13,10.411190,4.000000e+07,NaN,True,2021-12-13,2021-12-23,2022-04-08,要约回购,维护公司价值及股东权益所必需,...,NaT,0.0000,0.00,0.00,0.000000,0.00,0.00,0.0000,False,蔚琮农业
60051,2022-04-29,10.490902,3.506349e+07,NaN,True,2022-04-29,2022-05-09,2022-08-29,竞价回购,股权激励或者员工持股计划,...,2022-06-24,0.0137,480204.65,10.83,0.000864,30278.81,83758.30,0.1744,False,蔚琮农业
60256,2023-03-03,12.176846,2.855223e+07,NaN,True,2023-03-03,2023-03-13,2023-09-07,竞价回购,维护公司价值及股东权益所必需,...,2023-03-23,0.0070,200286.06,11.14,0.000000,0.18,200285.96,1.0000,True,蔚琮农业
60417,2023-11-06,5.317517,2.699380e+07,NaN,True,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,2023-11-08,0.0094,253996.00,0.00,0.000000,0.00,105733.67,0.4163,False,蔚琮农业

In [194]:
df[['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']]

,日期,决议通过日,实施开始日,实施截止日,上市日期,公告日期,出售开始日,出售截止日
0,2020-01-02,NaT,NaT,NaT,2021-07-01,NaT,NaT,NaT
1,2020-01-03,NaT,NaT,NaT,2021-07-01,NaT,NaT,NaT
2,2020-01-06,NaT,NaT,NaT,2021-07-01,NaT,NaT,NaT
3,2020-01-07,NaT,NaT,NaT,2021-07-01,NaT,NaT,NaT
4,2020-01-08,NaT,NaT,NaT,2021-07-01,NaT,NaT,NaT
...,...,...,...,...,...,...,...,...
60695,2024-12-25,2023-11-06,2023-11-16,2024-05-07,2021-07-15,2024-10-27,NaT,NaT
60696,2024-12-26,2023-11-06,2023-11-16,2024-05-07,2021-07-15,2024-10-27,NaT,NaT
60697,2024-12-27,2023-11-06,2023-11-16,2024-05-07,2021-07-15,2024-10-27,NaT,NaT
60698,2024-12-30,2023-11-06,2023-11-16,2024-05-07,2021-07-15,2024-10-27,NaT,NaT
60699,2024-12-31,2023-11-06,2023-11-16,2024-05-07,2021-07-15,2024-10-27,NaT,NaT

In [195]:
df['决议通过日'][33302]

Timestamp('2021-12-31 00:00:00')

In [196]:
df['日期'][33302]

Timestamp('2022-02-28 00:00:00')

In [197]:
df['日期'][33302] == df['决议通过日'][33302]

False

# Law Article 4

## MEU_4_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 因维护公司价值及股东权益所必需回购股份的 |
| constraint | 应当符合以下条件之一：（一）公司股票收盘价格低于最近一期每股净资产；（二）连续20个交易日内公司股票收盘价格跌幅累计达到20%；（三）公司股票收盘价格低于最近一年股票最高收盘价格的50%；（四）中国证券监督管理委员会（以下简称中国证监会）规定的其他条件。 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1855 |
| completion_tokens | 4160 |

### 代码实现

In [198]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [199]:
import pandas as pd

def check_meu_4_1(df):
    '''
    检查MEU_4_1合规性：
    - subject: 上市公司（所有记录自动满足）
    - condition: 通过了维护公司价值及股东权益所必需的回购决议
    - constraint: 需满足四个价格条件之一（仅验证前三项）
    '''
    df = df.copy()

    # 初始化合规标记列
    df['meu_4_1_subject'] = True  # 所有记录均为上市公司
    df['meu_4_1_condition'] = False
    df['meu_4_1_constraint'] = None

    # 标记condition条件（存在特定目的的回购方案）
    valid_condition = (df['存在回购方案'] & (df['回购用途'] == '维护公司价值及股东权益所必需') & (df['日期'] == df['决议通过日'])) 
    df['meu_4_1_condition'] = valid_condition

    # 计算constraint的三个可验证条件
    # 条件1：收盘价低于每股净资产
    condition1 = df['收盘价'] < df['每股净资产']

    # 条件2：20交易日累计跌幅20%（按公司分组计算）
    df['20d_prior_close'] = df.groupby('公司简称')['收盘价'].shift(20)
    price_drop = (df['收盘价'] - df['20d_prior_close']) / df['20d_prior_close']
    condition2 = price_drop <= -0.2

    # 条件3：低于一年最高价50%（滚动250交易日窗口）
    df['1y_high'] = df.groupby('公司简称')['收盘价'].transform(
        lambda x: x.rolling(250, min_periods=1).max()
    )
    condition3 = df['收盘价'] < (df['1y_high'] * 0.5)

    # 合并有效约束条件（前三项）
    valid_constraint = condition1 | condition2 | condition3
    
    # 标记constraint列
    df['meu_4_1_constraint'] = valid_constraint.astype(bool)
    
    # 清理中间计算列
    df.drop(['20d_prior_close', '1y_high'], axis=1, inplace=True, errors='ignore')

    return df

In [200]:
df = check_meu_4_1(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_4_1_subject,meu_4_1_condition,meu_4_1_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True

In [201]:
df['meu_4_1_condition'].sum()

np.int64(132)

In [202]:
df['meu_4_1_constraint'].sum()

np.int64(6698)

In [203]:
# df.to_csv('temp_bse04.csv', encoding='utf-8-sig', index=False)

---

# Law Article 13

## MEU_13_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 实施竞价回购 |
| constraint | 应当符合公司股票上市已满6个月 |
| contextual_info | nan |
| note | 假设公司股票上市日为最早的收盘价非空的日期 |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1800 |
| completion_tokens | 1896 |

### 代码实现

In [204]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [205]:
import pandas as pd

def check_meu_13_1(df):
    '''
    验证MEU_13_1合规性:
    - subject: 上市公司
    - condition: 实施竞价回购
    - constraint: 上市已满6个月
    
    参数说明:
    df: 包含公司每日状态的面板数据，必须包含['上市日期','日期','回购方式']列
    
    验证逻辑:
    1. 所有公司默认满足subject条件（均为上市公司）
    2. 当回购方式为竞价交易时满足condition
    3. 当当前日期距离上市日期满6个月时满足constraint
    '''
    
    df = df.copy()
    
    # 初始化标记列
    df['meu_13_1_subject'] = True  # 所有公司均为上市公司
    df['meu_13_1_condition'] = False
    df['meu_13_1_constraint'] = None
    
    # 标记condition条件（实施竞价回购）
    is_auction_repurchase = df['回购方式'] == '竞价回购'
    df.loc[is_auction_repurchase, 'meu_13_1_condition'] = True
    
    # 标记constraint条件（上市满6个月）
    # 计算上市日期+6个月后的日期
    six_months_after = df['上市日期'] + pd.DateOffset(months=6)
    # 比较当前日期是否满足时间要求（包含等于）
    valid_constraint = df['日期'] >= six_months_after
    df.loc[valid_constraint, 'meu_13_1_constraint'] = True
    df.loc[~valid_constraint, 'meu_13_1_constraint'] = False
    
    return df

In [206]:
df = check_meu_13_1(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_13_1_subject,meu_13_1_condition,meu_13_1_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True

---

## MEU_13_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 实施竞价回购 |
| constraint | 应当符合公司最近1年无重大违法行为 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1789 |
| completion_tokens | 4860 |

### 代码实现

In [207]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [208]:
import pandas as pd
from bisect import bisect_left, bisect_right

def check_meu_13_2(df):
    '''
    合规性检查函数，针对MEU_13_2条款：
    - subject: 上市公司
    - condition: 实施竞价回购
    - constraint: 最近1年无重大违法行为
    
    参数说明：
    df : 包含上市公司每日状态数据的DataFrame
    
    返回：
    添加合规性标记后的DataFrame
    '''
    df = df.copy()

    # 初始化标记列
    df['meu_13_2_subject'] = True  # 所有公司均为上市公司
    df['meu_13_2_condition'] = False
    df['meu_13_2_constraint'] = None

    # condition: 实施竞价回购
    valid_condition = df['存在回购方案'] & (df['回购方式'] == '竞价回购')
    df.loc[valid_condition, 'meu_13_2_condition'] = True

    # constraint: 最近1年无重大违法行为
    # 预处理：获取每个公司的重大违法日期列表（已排序）
    df_sorted = df.sort_values(['公司简称', '日期'])
    violation_mask = df_sorted['公司法律情况'] == '重大违法行为'
    violations = df_sorted[violation_mask][['公司简称', '日期']]
    
    # 将日期转换为Timestamp并排序存储
    violation_dict = violations.groupby('公司简称')['日期'].apply(
        lambda x: sorted(pd.to_datetime(x).tolist())
    ).to_dict()

    # 定义检查函数（使用二分查找优化）
    def check_constraint(row):
        company = row['公司简称']
        current_date = pd.to_datetime(row['日期'])
        start_date = current_date - pd.DateOffset(years=1)
        
        # 获取该公司的违法日期列表
        v_dates = violation_dict.get(company, [])
        if not v_dates:
            return True
        
        # 执行二分查找
        left = bisect_left(v_dates, start_date)
        right = bisect_right(v_dates, current_date)
        return not (left < right)  # 存在违法时返回False

    # 计算约束条件标记
    df['meu_13_2_constraint'] = df.apply(check_constraint, axis=1)

    return df

In [209]:
df = check_meu_13_2(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_13_2_subject,meu_13_2_condition,meu_13_2_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True

In [210]:
df.to_csv('temp_bse04.csv', encoding='utf-8-sig', index=False)

---

## MEU_13_7


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 因触及本指引第四条规定条件而启动回购并减少注册资本 |
| constraint | 不适用股票上市已满6个月的要求 |
| contextual_info | nan |
| note | nan |
| relation | exclude |
| target | MEU_13_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1799 |
| completion_tokens | 6697 |

### 代码实现

In [211]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [212]:
import pandas as pd

def check_meu_13_7(df):
    '''
    合规性检查函数，用于验证MEU_13_7条款的遵守情况
    subject: 上市公司
    condition: 因触及本指引第四条规定条件而启动回购并减少注册资本
    constraint: 不适用股票上市已满6个月的要求
    '''
    df = df.copy()

    # 初始化标记列
    df['meu_13_7_subject'] = True  # 所有公司均为上市公司
    df['meu_13_7_condition'] = False
    df['meu_13_7_constraint'] = None

    # 计算第四条的三个可验证条件
    # 条件1：收盘价低于每股净资产
    condition1 = df['收盘价'] < df['每股净资产']

    # 条件2：20交易日累计跌幅20%（按公司分组计算）
    df['20d_prior_close'] = df.groupby('公司简称')['收盘价'].shift(20)
    return_20_day = (df['收盘价'] - df['20d_prior_close']) / df['20d_prior_close']
    condition2 = return_20_day <= -0.2

    # 条件3：低于一年最高价50%（滚动250交易日窗口）
    df['1y_high'] = df.groupby('公司简称')['收盘价'].transform(
        lambda x: x.rolling(250, min_periods=1).max()
    )
    condition3 = df['收盘价'] < (df['1y_high'] * 0.5)

    # 合并有效约束条件（前三项）
    valid_condition = condition1 | condition2 | condition3
    
    # 记录condition
    df['meu_13_7_condition'] = valid_condition

    # 约束验证：默认为None
    df['meu_13_7_constraint'] = None

    return df

In [213]:
df = check_meu_13_7(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_13_7_subject,meu_13_7_condition,meu_13_7_constraint,20d_prior_close,1y_high
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,True,None,5.333217,6.782152
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,True,None,5.279715,6.782152
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,True,None,5.410009,6.782152
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,True,None,5.184603,6.782152
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,True,None,5.259311,6.782152

In [214]:
df['meu_13_7_condition'].sum()

np.int64(6698)

---

# Law Article 15

## MEU_15_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | nan |
| constraint | 在回购股份方案中明确拟回购股份数量或者资金总额的上下限，且下限不得低于上限的50% |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1802 |
| completion_tokens | 6138 |

### 代码实现

In [215]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [216]:
import pandas as pd

def check_meu_15_2(df):
    '''
    检查MEU_15_2合规性:
    subject: 上市公司
    condition: NaN(无条件触发)
    constraint: 回购方案需明确数量/资金上下限且下限≥50%上限
    '''
    df = df.copy()

    # 初始化合规标记列
    df['meu_15_2_subject'] = True  # 所有公司均为上市公司
    df['meu_15_2_condition'] = True  # 无条件要求，全部视为满足
    df['meu_15_2_constraint'] = None  # 初始化为None

    # 标记constraint合规性
    # 不存在回购方案的行自动合规
    df.loc[~df['存在回购方案'], 'meu_15_2_constraint'] = True

    # 处理存在回购方案的行
    mask = df['存在回购方案']
    
    # 计算数量合规性 (下限≥50%上限)
    quantity_valid = (
        df['回购数量下限'] >= df['回购数量上限'] * 0.5
    ) & (
        df['回购数量上限'].notna()  # 确保已明确设置数量上限
    )
    
    # 计算资金合规性 (下限≥50%上限)
    funds_valid = (
        df['资金总额下限'] >= df['资金总额上限'] * 0.5
    ) & (
        df['资金总额上限'].notna()  # 确保已明确设置资金上限
    )
    
    # 合并合规条件
    combined_valid = quantity_valid | funds_valid
    
    # 更新约束
    df.loc[mask, 'meu_15_2_constraint'] = combined_valid[mask]

    return df

In [217]:
df = check_meu_15_2(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_15_2_subject,meu_15_2_condition,meu_15_2_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,True,True
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,True,True
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,True,True
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,True,True
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True

In [218]:
df['meu_15_2_constraint'].sum()

50838

---

# Law Article 16

## MEU_16_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 进行竞价回购 |
| constraint | 价格上限原则上不应高于董事会审议通过回购股份决议前30个交易日（不含停牌日）交易均价的200% |
| contextual_info | nan |
| note | 不考虑"原则上"的松弛条件 |
| relation | refer_to |
| target | MEU_75_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1877 |
| completion_tokens | 7910 |

### 代码实现

In [219]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [220]:
def check_meu_16_1(df):
    '''
    检查MEU_16_1合规性：
    - subject: 上市公司（所有行自动满足）
    - condition: 存在竞价回购行为
    - constraint: 申报价格不超过决议前30日交易均价200%
    注：每日股价以收盘价为准, 不考虑日内价格变化; 不存在这30个交易日无法取到的情况
    '''
    df = df.copy()
    
    # 1. 标记subject（所有公司均为上市公司）
    df['meu_16_1_subject'] = True
    
    # 2. 标记condition
    df['meu_16_1_condition'] = df['存在回购方案'] & (df['回购方式'] == '竞价回购')
    
    # 3. 初始化constraint
    df['meu_16_1_constraint'] = None
    
    # 处理constraint部分
    for company_name, company_group in df.groupby('公司简称'):
        # 筛选该公司的回购方案（存在回购方案且是竞价回购）
        repo_mask = company_group['存在回购方案']
        repo_cases = company_group[repo_mask]
        d_list = repo_cases['决议通过日'].unique()
        
        for d in d_list:
            # 获取该决议通过日的实施开始日和截止日
            case_rows = repo_cases[repo_cases['决议通过日'] == d]
            if len(case_rows) == 0:
                continue
            case_row = case_rows.iloc[0]
            s = case_row['决议通过日']
            e = case_row['实施截止日']
            
            # 计算前30日的收盘价均價
            before_d_mask = company_group['日期'] < d
            before_d = company_group[before_d_mask]
            
            last_30 = before_d.tail(30)
            avg_price = last_30['收盘价'].mean()
            ref_price = avg_price * 2
            
            # 找到实施期间内的行
            mask_period = (company_group['日期'] >= s) & (company_group['日期'] <= e)
            mask_to_check = mask_period & company_group['申报价格'].notna()
            indices = company_group[mask_to_check].index
            
            # 更新constraint列
            if not indices.empty:
                constraint_values = company_group.loc[indices, '申报价格'] <= ref_price
                df.loc[indices, 'meu_16_1_constraint'] = constraint_values
                df.loc[indices, '违规价格上限'] = ref_price
                df.loc[indices, '前30日收盘价均值'] = avg_price 
    
    return df

In [221]:
df = check_meu_16_1(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_16_1_subject,meu_16_1_condition,meu_16_1_constraint,违规价格上限,前30日收盘价均值
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaN,NaN
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaN,NaN
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaN,NaN
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaN,NaN
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaN,NaN

In [222]:
df['meu_16_1_condition'].sum()

np.int64(13336)

In [223]:
df['meu_16_1_constraint'].sum()

16899

In [224]:
df.to_csv('temp_bse04.csv', encoding='utf-8-sig', index=False)

---

# Law Article 18

## MEU_18_7


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 进行股份回购的申报 |
| constraint | 申报价格不得为公司股票当日交易涨幅限制的价格 |
| contextual_info | nan |
| note | 假设当日涨跌幅限制为前日收盘价的正负10% |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1806 |
| completion_tokens | 5234 |

### 代码实现

In [225]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [226]:
import pandas as pd

def check_meu_18_7(df):
    '''
    验证MEU_18_7合规性:
    - subject: 上市公司
    - condition: 进行股份回购的申报
    - constraint: 申报价格不得为当日涨跌幅限制价格
    '''
    df = df.copy()

    # 初始化合规性标记列
    df['meu_18_7_subject'] = True  # 所有公司均为上市公司
    df['meu_18_7_condition'] = False
    df['meu_18_7_constraint'] = None

    # 1. 标记condition条件满足情况
    # 条件成立需同时满足：存在回购方案且存在申报价格
    has_repo_plan = df['存在回购方案']
    has_declaration = df['申报价格'].notna()
    valid_condition = has_repo_plan & has_declaration & (df['日期'] == df['决议通过日'])
    df.loc[valid_condition, 'meu_18_7_condition'] = True

    # 2. 标记constraint约束满足情况
    # 计算前收盘价的±10%涨跌幅限制
    prev_close = df['前收盘价']
    upper_limit = prev_close * 1.1
    lower_limit = prev_close * 0.9
    
    # 获取申报价格并判断是否触及限制
    declared_price = df['申报价格']
    bigger_than_upper = declared_price >= upper_limit
    smaller_than_lower = declared_price <= lower_limit
    
    # 有效约束条件：存在申报价格且不触及涨跌停价
    valid_constraint = has_declaration & ~(bigger_than_upper | smaller_than_lower)
    df['meu_18_7_constraint'] = valid_constraint

    return df

In [227]:
df = check_meu_18_7(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_18_7_subject,meu_18_7_condition,meu_18_7_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False

In [228]:
df['meu_18_7_constraint'].sum()

np.int64(14428)

---

# Law Article 19

## MEU_19_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 实施竞价回购 |
| constraint | 实施期限不超过12个月 |
| contextual_info | 自董事会或股东大会（如须）审议通过回购股份决议之日起算 |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1800 |
| completion_tokens | 4633 |

### 代码实现

In [229]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [230]:
import pandas as pd

def check_meu_19_1(df):
    '''
    合规性检查函数，用于验证MEU_19_1条款的遵守情况：
    - subject: 上市公司（所有行自动满足）
    - condition: 实施竞价回购（需同时满足存在回购方案和回购方式为竞价）
    - constraint: 实施期限不超过12个月（基于决议通过日与实施截止日的时间差）
    '''
    df = df.copy()

    # 初始化标记列
    df['meu_19_1_subject'] = True  # 所有公司均为上市公司
    df['meu_19_1_condition'] = False
    df['meu_19_1_constraint'] = None

    # 标记条件：存在回购方案且回购方式为竞价
    is_auction_repurchase = (
        df['存在回购方案'] & 
        (df['回购方式'] == '竞价回购')
    )
    df.loc[is_auction_repurchase, 'meu_19_1_condition'] = True

    # 标记约束：实施期限不超过12个月
    # 仅当日期字段有效时进行计算
    valid_dates = df['决议通过日'].notna() & df['实施截止日'].notna()
    date_mask = valid_dates & (
        df['实施截止日'] <= df['决议通过日'] + pd.DateOffset(months=12)
    )
    df.loc[date_mask, 'meu_19_1_constraint'] = True
    df.loc[~date_mask, 'meu_19_1_constraint'] = False

    return df

In [231]:
df = check_meu_19_1(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_19_1_subject,meu_19_1_condition,meu_19_1_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True

---

## MEU_19_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 因维护公司价值及股东权益所必需回购股份的，实施竞价回购 |
| constraint | 回购实施期限自股东大会或者董事会审议通过最终回购股份方案之日起不超过3个月 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1810 |
| completion_tokens | 4004 |

### 代码实现

In [232]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [233]:
import pandas as pd

def check_meu_19_2(df):
    '''
    检查MEU_19_2合规性：
    "subject": "上市公司", 
    "condition": "因维护公司价值及股东权益所必需回购股份的，实施竞价回购", 
    "constraint": "回购实施期限自股东大会或者董事会审议通过最终回购股份方案之日起不超过3个月", 
    "contextual_info": NaN
    '''
    df = df.copy()

    # 初始化合规标记列
    df['meu_19_2_subject'] = True  # 所有公司都是上市公司
    df['meu_19_2_condition'] = False
    df['meu_19_2_constraint'] = None

    # 1. 标记condition合规性
    # 条件需同时满足：存在回购方案、维护公司价值用途、竞价回购方式
    condition_mask = (
        df['存在回购方案'] &
        (df['回购用途'] == '维护公司价值及股东权益所必需') &
        (df['回购方式'] == '竞价回购')
    )
    df.loc[condition_mask, 'meu_19_2_condition'] = True

    # 2. 标记constraint合规性
    # 约束需同时满足：存在回购方案、实施截止日在决议通过日3个月内
    constraint_mask = df['存在回购方案'].copy()
    # 计算自然日边界（使用pd.DateOffset处理月份差异）
    deadline = df['决议通过日'] + pd.DateOffset(months=3)
    # 处理NaT避免类型错误（当存在回购方案为False时自动返回False）
    constraint_mask = constraint_mask & (df['实施截止日'] <= deadline)
    df.loc[constraint_mask, 'meu_19_2_constraint'] = True
    df.loc[~constraint_mask, 'meu_19_2_constraint'] = False

    return df

In [234]:
df = check_meu_19_2(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_19_2_subject,meu_19_2_condition,meu_19_2_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False

---

# Law Article 21

## MEU_21_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 回购股份用于股权激励或者员工持股计划、转换上市公司发行的可转换为股票的公司债券、维护公司价值及股东权益所必需的 |
| constraint | 合计持有的本公司股份数不得超过本公司已发行股份总额的10% |
| contextual_info | nan |
| note | nan |
| relation | exclude |
| target | MEU_9_3 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1818 |
| completion_tokens | 2571 |

### 代码实现

In [235]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [236]:
import pandas as pd

def check_meu_21_2(df):
    '''
    验证MEU_21_2合规性:
    "subject": "上市公司",
    "condition": "回购股份用于股权激励或者员工持股计划、转换上市公司发行的可转换为股票的公司债券、维护公司价值及股东权益所必需的",
    "constraint": "合计持有的本公司股份数不得超过本公司已发行股份总额的10%",
    "contextual_info": NaN
    '''

    df = df.copy()

    # 初始化标记列
    df['meu_21_2_subject'] = True  # 所有记录主体均为上市公司
    df['meu_21_2_condition'] = False
    df['meu_21_2_constraint'] = None

    # 1. 标记condition有效性
    valid_uses = [
        '股权激励或者员工持股计划',
        '转换上市公司发行的可转换为股票的公司债券',
        '维护公司价值及股东权益所必需'
    ]
    df['meu_21_2_condition'] = df['回购用途'].isin(valid_uses)

    # 2. 标记constraint有效性
    # 处理空值并计算回购比例
    total_shares = df['总股本'].replace(0, pd.NA)  # 防止除零错误
    cumulative_repo = df['累计回购数量'].fillna(0)
    repo_ratio = cumulative_repo / total_shares
    
    # 约束条件判断
    valid_constraint = (repo_ratio <= 0.1) & (~total_shares.isna())
    df['meu_21_2_constraint'] = valid_constraint.astype(bool)

    return df

In [237]:
df = check_meu_21_2(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_21_2_subject,meu_21_2_condition,meu_21_2_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,True,True

---

# Law Article 42

## MEU_42_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 因维护公司价值及股东权益所必需而回购股份的，处于上市公司定期报告、业绩预告或者业绩快报披露前10个交易日内（因特殊原因推迟定期报告披露日期的，自原预约公告日前10个交易日起算，至披露前1个交易日） |
| constraint | 不得采用集中竞价交易方式出售股份 |
| contextual_info | nan |
| note | 简化假设: 不考虑报告推迟情况 |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1853 |
| completion_tokens | 9520 |

### 代码实现

In [238]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [239]:
import pandas as pd

def check_meu_42_2(df):
    '''
    合规性检查函数，对应MEU_42_2条款：
    - subject: 上市公司
    - condition: 因维护公司价值及股东权益回购股份且处于定期报告披露前10个交易日内
    - constraint: 不得采用集中竞价交易方式出售股份
    '''
    df = df.copy()

    # 初始化标记列
    df['meu_42_2_subject'] = True  # 所有公司均为上市公司
    df['meu_42_2_condition'] = False
    df['meu_42_2_constraint'] = None

    # 1. 计算时间窗口条件（condition的时间部分）
    # 获取所有定期报告类公告日期
    report_mask = df['公告类型'].isin(['季报', '年报', '半年报'])
    valid_announcements = df[report_mask][['公司简称', '公告日期']].drop_duplicates()
    
    # 计算时间窗口标记列
    df['_temp_in_window'] = False
    
    # 为每个公司生成交易日历
    for company in valid_announcements['公司简称'].unique():
        # 获取该公司的所有交易日
        company_trading_days = df[df['公司简称'] == company]['日期'].unique()
        company_trading_days = pd.Series(company_trading_days).sort_values().reset_index(drop=True)
        
        # 获取该公司的所有公告日期
        company_announcements = valid_announcements[valid_announcements['公司简称'] == company]['公告日期']
        
        for ann_date in company_announcements:
            # 找到公告日期在交易日序列中的位置（或最接近的交易日前的位置）
            # 如果公告日期不是交易日，找到它之后的第一个交易日
            if ann_date in company_trading_days.values:
                ann_idx = company_trading_days[company_trading_days == ann_date].index[0]
            else:
                # 找到第一个大于公告日期的交易日
                later_days = company_trading_days[company_trading_days > ann_date]
                if len(later_days) > 0:
                    ann_idx = company_trading_days[company_trading_days == later_days.iloc[0]].index[0]
                else:
                    # 如果没有之后的交易日，跳过这个公告
                    continue
                
            # 计算前10个交易日的起始位置
            start_idx = max(0, ann_idx - 10)
            start_date = company_trading_days[start_idx]
            
            # 标记窗口期内的日期
            window_mask = (df['公司简称'] == company) & \
                          (df['日期'] >= start_date) & \
                          (df['日期'] < ann_date)
            df.loc[window_mask, '_temp_in_window'] = True

    # 2. 标记condition条件
    usage_condition = df['回购用途'] == '维护公司价值及股东权益所必需'
    df['meu_42_2_condition'] = usage_condition & df['_temp_in_window']

    # 3. 标记constraint条件（独立检查）
    # 集中竞价出售包含计划申报和实际成交两种情形
    sell_condition = df['存在出售计划'] | (df['当日出售数量'] > 0)
    df['meu_42_2_constraint'] = ~sell_condition

    # 清理临时列
    df.drop(columns=['_temp_in_window'], inplace=True, errors='ignore')

    return df

In [240]:
df = check_meu_42_2(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_42_2_subject,meu_42_2_condition,meu_42_2_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False

In [241]:
# df.to_csv('temp_bse04.csv', encoding='utf-8-sig', index=False)

---

# Law Article 45

## MEU_45_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 采用集中竞价交易方式出售已回购股份 |
| constraint | 申报价格不得为公司股票当日交易跌幅限制的价格 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1796 |
| completion_tokens | 8055 |

### 代码实现

In [242]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [243]:
import pandas as pd

def check_meu_45_2(df):
    '''
    检查MEU_45_2的合规性：
    subject: 上市公司（所有行均为上市公司）
    condition: 采用集中竞价交易方式出售已回购股份（存在出售计划即视为满足）
    constraint: 申报价格必须在涨跌停区间内（前收盘价的90%~110%之间，含边界）
                合规：价格在区间内（False）
                违规：价格超出区间（True）
    '''
    df = df.copy()

    # 初始化标记列
    df['meu_45_2_subject'] = True  # 所有公司均为上市公司
    df['meu_45_2_condition'] = df['存在出售计划']  # 本案例中'出售'均为集中竞价方式
    df['meu_45_2_constraint'] = None 

    # 计算涨跌停价（前收盘价的±10%）
    df['_temp_lower_limit'] = df['前收盘价'] * 0.9  # 跌停价
    df['_temp_upper_limit'] = df['前收盘价'] * 1.1  # 涨停价
    
    # 判断申报价格是否在涨跌停区间内（含边界）
    within_limit = (df['申报价格'] >= df['_temp_lower_limit']) & (df['申报价格'] <= df['_temp_upper_limit'])
    
    # 标记约束有效性（True=违规，False=合规）
    df['meu_45_2_constraint'] = ~within_limit  # 超出区间则违规（True）

    # 清理临时列
    df.drop(columns=['_temp_lower_limit', '_temp_upper_limit'], inplace=True)

    return df

In [244]:
df = check_meu_45_2(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_45_2_subject,meu_45_2_condition,meu_45_2_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True

---

## MEU_45_3


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 采用集中竞价交易方式出售已回购股份且每日出售数量超过10万股 |
| constraint | 每日出售的数量不得超过出售计划披露日前20个交易日日均盘中成交量的25% |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1810 |
| completion_tokens | 8673 |

### 代码实现

In [245]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [246]:
def check_meu_45_3(df):
    '''
    检查MEU_45_3合规性：
    subject: 上市公司
    condition: 采用集中竞价交易方式出售已回购股份且每日出售数量超过10万股
    constraint: 每日出售数量不得超过出售计划披露日前20个交易日日均盘中成交量的25%
    '''
    df = df.copy()

    # 初始化标记列
    df['meu_45_3_subject'] = True  # 所有记录均为上市公司
    df['meu_45_3_condition'] = False
    df['meu_45_3_constraint'] = None 

    # 1. 标记condition条件
    # 条件需同时满足：存在出售计划、采用集中竞价方式（隐含在存在出售计划中）、当日出售数量>10万
    valid_condition = df['存在出售计划'] & (df['当日出售数量'] > 100000)
    df.loc[valid_condition, 'meu_45_3_condition'] = True

    # 2. 标记constraint约束（独立检查所有记录）
    # 预处理：计算每个公司每个披露日前20日成交量均值
    # 假设存在'成交量'列且'公告日期'为计划披露日
    # 按公司分组处理
    for company in df['公司简称'].unique():
        company_df = df[df['公司简称'] == company].sort_values('日期')
        
        # 创建日期索引
        company_dates = company_df.set_index('日期')
        
        # 遍历该公司的所有记录
        for idx, row in company_df.iterrows():
            disclosure_date = row['出售计划披露日']
            if pd.isnull(disclosure_date):
                continue
            
            # 获取披露日前20个交易日的成交量
            # 筛选披露日前的交易日
            prior_dates = company_dates[company_dates.index < disclosure_date].index
            
            # 获取最近的20个交易日
            last_20_trading_days = prior_dates[-20:]
            prior_sessions = company_dates.loc[last_20_trading_days]
            
            avg_volume = prior_sessions['成交量'].mean()
            threshold = avg_volume * 0.25
            current_sell = row['当日出售数量']
            
            # 标记约束满足情况
            if current_sell <= threshold:
                df.loc[idx, 'meu_45_3_constraint'] = True
            else:
                df.loc[idx, 'meu_45_3_constraint'] = False


    return df

In [247]:
df = check_meu_45_3(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_45_3_subject,meu_45_3_condition,meu_45_3_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None

In [248]:
df['meu_45_3_condition'].sum()

np.int64(782)

In [249]:
df['meu_45_3_constraint'].sum()

27898

---

## MEU_45_4


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 采用集中竞价交易方式出售已回购股份 |
| constraint | 在任意连续90日内，出售股份的总数不得超过公司股份总数的1% |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1802 |
| completion_tokens | 5301 |

### 代码实现

In [250]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [ ]:
import pandas as pd

def check_meu_45_4(df):
    '''
    检查MEU_45_4合规性：
    - subject: 上市公司（所有行自动满足）
    - condition: 存在集中竞价出售已回购股份计划
    - constraint: 90交易日累计出售量≤总股本1%
    '''
    df = df.copy()

    # 初始化合规标记列
    df['meu_45_4_subject'] = True  # 所有公司均为上市公司
    df['meu_45_4_condition'] = df['存在出售计划'].astype(bool)  # 存在出售计划即满足条件
    df['meu_45_4_constraint'] = None  # 初始化为空值

    # 按公司分组计算滚动累计出售量
    df.sort_values(['公司简称', '日期'], inplace=True)
    df['90交易日累计出售'] = df.groupby('公司简称')['当日出售数量'].transform(
        lambda x: x.rolling(90, min_periods=1).sum()
    )

    # 计算总股本1%阈值并验证约束
    threshold = df['总股本'] * 0.01
    df['meu_45_4_constraint'] = df['90交易日累计出售'] <= threshold

    # 清理中间列
    df.drop(columns=['90交易日累计出售'], inplace=True)

    return df

In [252]:
df = check_meu_45_4(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_45_4_subject,meu_45_4_condition,meu_45_4_constraint
26708,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.000000,0.00,0.0,0.0,False,旻琨交通,True,False,True
26709,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.000000,0.00,0.0,0.0,False,旻琨交通,True,False,True
26710,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.000000,0.00,0.0,0.0,False,旻琨交通,True,False,True
26711,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.000000,0.00,0.0,0.0,False,旻琨交通,True,False,True
26712,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.000000,0.00,0.0,0.0,False,旻琨交通,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53411,2024-12-25,20.651746,1.811811e+07,NaN,False,2024-04-29,2024-05-09,2024-06-11,竞价回购,维护公司价值及股东权益所必需,...,22.46,0.002849,51610.24,0.0,0.0,False,麒瑄控股,True,False,False
53412,2024-12-26,21.505517,1.811811e+07,NaN,False,2024-04-29,2024-05-09,2024-06-11,竞价回购,维护公司价值及股东权益所必需,...,22.46,0.002849,51610.24,0.0,0.0,False,麒瑄控股,True,False,False
53413,2024-12-27,20.754707,1.811811e+07,NaN,False,2024-04-29,2024-05-09,2024-06-11,竞价回购,维护公司价值及股东权益所必需,...,22.46,0.002849,51610.24,0.0,0.0,False,麒瑄控股,True,False,False
53414,2024-12-30,21.039916,1.811811e+07,NaN,False,2024-04-29,2024-05-09,2024-06-11,竞价回购,维护公司价值及股东权益所必需,...,22.46,0.002849,51610.24,0.0,0.0,False,麒瑄控股,True,False,False
53415,2024-12-31,21.020495,1.811811e+07,NaN,False,2024-04-29,2024-05-09,2024-06-11,竞价回购,维护公司价值及股东权益所必需,...,22.46,0.002849,51610.24,0.0,0.0,False,麒瑄控股,True,False,False

In [253]:
df['meu_45_4_constraint'].sum()

np.int64(37620)

---

# Law Article 46

## MEU_46_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 采用集中竞价交易方式出售已回购股份期间 |
| constraint | 首次出售已回购股份事实发生后应当在次1个交易日内披露出售进展情况公告 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1806 |
| completion_tokens | 9458 |

### 代码实现

In [254]:
# 读取模拟数据c
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [255]:

def check_meu_46_2(df):
    '''
    检查MEU_46_2合规性：
    "subject": "上市公司", 
    "condition": "采用集中竞价交易方式出售已回购股份期间", 
    "constraint": "首次出售已回购股份事实发生后应当在次1个交易日内披露出售进展情况公告"
    '''
    df = df.copy()
    
    # 1. 初始化标记列
    df['meu_46_2_subject'] = True  # 所有公司都是上市公司
    df['meu_46_2_condition'] = False
    df['meu_46_2_constraint'] = None
    
    # 2. 标记condition
    # 筛选存在集中竞价出售计划的行
    has_plan = df['存在出售计划'] == True
    df['meu_46_2_condition'] = has_plan
    
    # 3 判断constraint
    # 3.1 判断是否在出售期间内
    mask_date_range = (df['日期'] >= df['出售开始日']) & (df['日期'] <= df['出售截止日'])
    
    # 3.2 准确计算首次出售日期（修复分组索引问题）
    group_cols = ['公司简称', '出售开始日', '出售截止日']
    
    # 生成分组首次出售日期（保持分组键结构）
    first_sale_df = (
        df.groupby(group_cols)
        .apply(
            lambda g: g.loc[
                (g['日期'] >= g.name[1]) & 
                (g['日期'] <= g.name[2]) & 
                (g['当日出售数量'] > 0), '日期'
            ].min() 
            if any(
                (g['日期'] >= g.name[1]) & 
                (g['日期'] <= g.name[2]) & 
                (g['当日出售数量'] > 0)
            )
            else pd.NaT
        )
        .reset_index(name='首次出售日期')
    )
    
    # 合并回原始数据（避免索引错位）
    df = df.merge(first_sale_df, on=group_cols, how='left')
    
    # 3.3 判断当前日期是否在首次出售之后
    mask_first_sale = (df['日期'] >= df['首次出售日期']) & (~df['首次出售日期'].isna())
    
    # 需要检查的条件
    valid_condition = has_plan & mask_date_range & mask_first_sale
    
    
    # 条件3：标记constraint（修复次交易日合并问题）
    # 步骤1：获取每个首次出售的次交易日
    df_sorted = df.sort_values(['公司简称', '日期'])
    df_sorted['次交易日'] = df_sorted.groupby('公司简称')['日期'].shift(-1)
    
    # 步骤2：建立精确映射关系（包含首次出售日期）
    first_sales = (
        df[valid_condition]
        .groupby(group_cols)[['首次出售日期']]  # 仅按分组键聚合
        .first()
        .reset_index()
    )
    first_sales = first_sales.merge(
        df_sorted[['公司简称', '日期', '次交易日']],
        left_on=['公司简称', '首次出售日期'],
        right_on=['公司简称', '日期'],
        how='left'
    ).drop(columns=['日期']).rename(columns={'次交易日': '要求披露日'})  # 清理冗余列
    
    # 步骤3：多键合并避免数据污染
    df = df.merge(
        first_sales,
        on=group_cols + ['首次出售日期'],
        how='left'
    )
    
    # 步骤4：验证次日披露情况
    valid_constraint = (
    (df['首次出售日期'].notna()) &
    (df['存在出售计划'] == True)
)
    df.loc[valid_constraint, 'meu_46_2_constraint'] = df[df['日期'] == df['要求披露日']]['披露出售进展']
    
    return df

In [256]:
df = check_meu_46_2(df)
df

/var/folders/0l/pjlf4pl90rx7ldkq7jx18ny00000gn/T/ipykernel_34930/2684280027.py:30: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_46_2_subject,meu_46_2_condition,meu_46_2_constraint,首次出售日期,要求披露日
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaT,NaT
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaT,NaT
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaT,NaT
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaT,NaT
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.0,False,祎煜环保,True,False,None,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaT,NaT
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaT,NaT
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaT,NaT
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaT,NaT
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,0.06,0.0,0.0,True,蔚琮农业,True,False,None,NaT,NaT

In [257]:
df['meu_46_2_condition'].sum()

np.int64(13058)

In [258]:
df['meu_46_2_constraint'].sum()

90

In [259]:
df.to_csv('temp_bse04.csv', encoding='utf-8-sig', index=False)

---

## MEU_46_3


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 采用集中竞价交易方式出售已回购股份期间 |
| constraint | 出售已回购股份占上市公司总股本的比例每增加1%, 应当在事实发生之日起3个交易日内披露出售进展情况公告 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1813 |
| completion_tokens | 9654 |

### 代码实现

In [260]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [261]:
import pandas as pd
import numpy as np

def check_meu_46_3(df):
    '''
    检查MEU_46_3合规性：
    subject: 上市公司（所有行自动满足）
    condition: 采用集中竞价交易方式出售已回购股份期间
    constraint: 出售已回购股份占上市公司总股本的比例每增加1%, 应当在事实发生之日起3个交易日内披露出售进展情况公告
    '''
    df = df.copy()
    
    # 初始化标记列
    df['meu_46_3_subject'] = True
    df['meu_46_3_condition'] = False
    df['meu_46_3_constraint'] = None

    # 标记存在出售计划的期间
    in_selling_period = df['存在出售计划']
    df.loc[in_selling_period, 'meu_46_3_condition'] = True

    violations = set()

    # 按公司分组处理
    grouped = df.groupby('公司简称')
    for company, group in grouped:
        # 筛选存在出售计划的期间
        selling_group = group[group['存在出售计划']]
        if selling_group.empty:
            continue
        
        sell_dates = set(selling_group['日期'])
        company_dates = group['日期'].tolist()
        
        # 计算前一日累计比例
        selling_group = selling_group.copy()
        selling_group['累计出售比例_prev'] = selling_group['累计出售比例'].shift(1)
        
        for idx, row in selling_group.iterrows():
            curr = row['累计出售比例']
            prev = row['累计出售比例_prev']
            
            if pd.isna(prev):
                continue
            
            # 计算跨过的整数百分点
            prev_pct = prev * 100
            curr_pct = curr * 100
            min_k = int(np.floor(prev_pct)) + 1
            max_k = int(np.floor(curr_pct))
            
            if min_k > max_k:
                continue
            
            # 生成所有触发k值
            for k in range(min_k, max_k + 1):
                trigger_date = row['日期']
                
                # 获取窗口期
                try:
                    trigger_idx = company_dates.index(trigger_date)
                except ValueError:
                    continue
                
                window_dates = company_dates[trigger_idx+1 : trigger_idx+4]
                
                # 检查窗口期披露情况
                window_mask = group['日期'].isin(window_dates)
                has_disclosure = group.loc[window_mask, '披露出售进展'].any()
                
                # 记录未披露的出售期间日期
                if not has_disclosure:
                    for date in window_dates:
                        if date in sell_dates:
                            violations.add((company, date))

    # 应用违规标记
    df.loc[in_selling_period, 'meu_46_3_constraint'] = True
    violation_mask = df.apply(lambda r: (r['公司简称'], r['日期']) in violations, axis=1)
    df.loc[violation_mask & in_selling_period, 'meu_46_3_constraint'] = False

    # 清理中间列
    df.drop(columns=['累计出售比例_prev'], inplace=True, errors='ignore')

    return df

In [262]:
df = check_meu_46_3(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_46_3_subject,meu_46_3_condition,meu_46_3_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,None

In [263]:
df['meu_46_3_condition'].sum()

np.int64(13058)

In [264]:
df['meu_46_3_constraint'].sum()

11344

In [265]:
df.to_csv('temp_bse04.csv', encoding='utf-8-sig', index=False)

---

# Law Article 50

## MEU_50_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 实施要约回购 |
| constraint | 要约期限不得少于30个自然日 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1788 |
| completion_tokens | 3462 |

### 代码实现

In [266]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [267]:
import pandas as pd

def check_meu_50_2(df):
    '''
    检查MEU_50_2合规性：
    "subject": "上市公司",
    "condition": "实施要约回购",
    "constraint": "要约期限不得少于30个自然日",
    "contextual_info": NaN
    '''
    df = df.copy()
    
    # 初始化合规标记列
    df['meu_50_2_subject'] = True  # 所有公司均为上市公司
    df['meu_50_2_condition'] = False
    df['meu_50_2_constraint'] = None
    
    # 标记valid的condition（存在回购方案且为要约回购）
    is_passed = df['存在回购方案']& (df['日期'] == df['决议通过日'])
    is_tender_offer = df['回购方式'] == '要约回购'
    df.loc[is_passed & is_tender_offer, 'meu_50_2_condition'] = True
    
    # 标记valid的constraint（自然日计算要约期限）
    # 处理NaN并转换为布尔值
    valid_constraint = (df['要约期限'] >= 30).fillna(False)
    df['meu_50_2_constraint'] = valid_constraint.astype(bool)
    
    return df

In [268]:
df = check_meu_50_2(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_50_2_subject,meu_50_2_condition,meu_50_2_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True

---

## MEU_50_3


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 实施要约回购 |
| constraint | 要约期限不得超过60个自然日 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1787 |
| completion_tokens | 3882 |

### 代码实现

In [269]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [270]:
import pandas as pd

def check_meu_50_3(df):
    '''
    合规性检查函数，对应MEU_50_3条款：
    - subject: 上市公司
    - condition: 实施要约回购
    - constraint: 要约期限不得超过60个自然日
    '''
    df = df.copy()

    # 初始化标记列
    df['meu_50_3_subject'] = True  # 所有公司均为上市公司
    df['meu_50_3_condition'] = False
    df['meu_50_3_constraint'] = None

    # 标记条件：实施要约回购（存在有效回购方案且回购方式为要约回购）
    valid_condition = (df['存在回购方案']) & (df['回购方式'] == '要约回购') & (df['日期'] == df['决议通过日'])
    df.loc[valid_condition, 'meu_50_3_condition'] = True

    # 标记约束：计算自然日差（需处理空值）
    has_valid_dates = df['实施开始日'].notna() & df['实施截止日'].notna()
    duration = (df['实施截止日'] - df['实施开始日']).dt.days
    valid_constraint = (duration <= 60) & has_valid_dates
    
    # 更新约束标记（独立检查，不依赖subject和condition）
    df.loc[valid_constraint, 'meu_50_3_constraint'] = True
    df.loc[~valid_constraint, 'meu_50_3_constraint'] = False

    return df

In [271]:
df = check_meu_50_3(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_50_3_subject,meu_50_3_condition,meu_50_3_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,False

---

# Law Article 51

## MEU_51_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 实施要约回购 |
| constraint | 要约价格不得低于回购股份方案公告日前30个交易日该种股票每日加权平均价的算术平均值 |
| contextual_info | nan |
| note | nan |
| relation | refer_to |
| target | Law_75 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 1865 |
| completion_tokens | 6265 |

### 代码实现

In [272]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_04.csv')
date_columns = ['日期', '决议通过日', '实施开始日', '实施截止日', '上市日期', '公告日期', '出售开始日', '出售截止日']
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [273]:
import pandas as pd

def check_meu_51_2(df):
    '''
    验证MEU_51_2合规性：
    - subject: 上市公司（所有行自动满足）
    - condition: 实施要约回购（回购方式为要约回购）
    - constraint: 要约价格不低于方案公告日前30个交易日平均价
    '''
    df = df.copy()

    # 初始化标记列
    df['meu_51_2_subject'] = True  # 所有公司均为上市公司
    df['meu_51_2_condition'] = df['回购方式'] == '要约回购'
    df['meu_51_2_constraint'] = None  # 默认设为False

    # 计算前30日交易均价逻辑（以成交量加权）
    # 步骤1：提取有效决议记录
    valid_resolutions = df[['公司简称', '决议通过日']].dropna().drop_duplicates()
    
    # 步骤2：计算每个决议对应的30日成交量加权均价
    avg_price_list = []
    for _, row in valid_resolutions.iterrows():
        company = row['公司简称']
        resolution_date = row['决议通过日']
        
        # 获取决议日前30个交易日数据
        company_data = df[(df['公司简称'] == company) & (df['日期'] < resolution_date)]
        sorted_dates = company_data.sort_values('日期', ascending=False)
        last_30 = sorted_dates.head(30)
        
        if len(last_30) == 30:
            # 计算成交量加权平均收盘价
            weighted_avg = (last_30['收盘价'] * last_30['成交量']).sum() / last_30['成交量'].sum()
            avg_price_list.append({
                '公司简称': company,
                '决议通过日': resolution_date,
                'ref_price': weighted_avg
            })

    # 步骤3：合并参考价格到主表
    if avg_price_list:
        ref_df = pd.DataFrame(avg_price_list)
        df = df.merge(ref_df, on=['公司简称', '决议通过日'], how='left')
        
        # 步骤4：执行价格比较（仅当要约价格和参考价均存在时）
        price_mask = df['要约价格'].notna() & df['ref_price'].notna()
        df.loc[price_mask, 'meu_51_2_constraint'] = df.loc[price_mask, '要约价格'] >= df.loc[price_mask, 'ref_price']
        
        # 清理临时列
        df.drop(columns=['ref_price'], inplace=True)

    return df

In [274]:
df = check_meu_51_2(df)
df

,日期,收盘价,总股本,公司法律情况,存在回购方案,决议通过日,实施开始日,实施截止日,回购方式,回购用途,...,当日出售价格,当日出售比例,当日出售数量,累计出售数量,累计出售比例,披露出售进展,公司简称,meu_51_2_subject,meu_51_2_condition,meu_51_2_constraint
0,2020-01-02,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
1,2020-01-03,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
2,2020-01-06,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
3,2020-01-07,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
4,2020-01-08,NaN,4.000000e+07,NaN,False,NaT,NaT,NaT,NaN,NaN,...,0.00,0.0,0.00,0.0,0.0,False,祎煜环保,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60695,2024-12-25,5.349832,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60696,2024-12-26,5.460649,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60697,2024-12-27,5.495233,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60698,2024-12-30,5.636345,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True
60699,2024-12-31,5.667665,1.861226e+07,NaN,False,2023-11-06,2023-11-16,2024-05-07,竞价回购,转换上市公司发行的可转换为股票的公司债券,...,5.18,0.0,0.06,0.0,0.0,True,蔚琮农业,True,False,True

---