In [1]:
# 读取模拟数据
import pandas as pd
import numpy as np
df = pd.read_csv('data_simulation/data_generated/data_simulate_10.csv')
date_columns = ["财务数据日期", "公告日期", "日期", "上市日期"]
for col in date_columns:
    df[col] = pd.to_datetime(df[col])
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,是否实施股票股利,是否公积金转增股本,相关股东前三个月内存在减持情形,相关股东后三个月存在减持计划,现金分红金额,送股比例,转增比例,是否进行权益分派,权益分派方案文本,公司简称
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,False,False,False,False,0.0,0,0,False,[],曦祺电力
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,False,False,False,False,0.0,0,0,False,[],曦祺电力
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,False,False,False,False,0.0,0,0,False,[],曦祺电力
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,False,False,False,False,0.0,0,0,False,[],曦祺电力
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,False,False,False,False,0.0,0,0,False,[],曦祺电力
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,False,False,True,False,0.0,0,0,False,[],蔚珵食品
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,False,False,True,False,0.0,0,0,False,[],蔚珵食品
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,False,False,False,False,0.0,0,0,False,[],蔚珵食品
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,True,False,False,False,0.0,1,0,True,['留存未分配利润的预计用途以及收益情况'],蔚珵食品
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,False,False,False,False,0.0,0,0,False,[],蔚珵食品

In [2]:
df.columns

Index(['财务数据日期', '公告类型', '公告日期', '审计意见', '再融资或并购导致净资产有较大变化', '总资产', '总负债',
       '净资产', '资产负债率', '交易性金融资产', '衍生金融资产', '债权投资', '其他债权投资', '其他权益工具投资',
       '其他非流动金融资产', '其他流动资产', '金融资产总额', '总股本', '每股净资产', '合并报表未分配利润',
       '母公司报表未分配利润', '营业收入', '归属于上市公司股东的净利润', '每股净利润', '母公司报表净利润',
       '经营活动现金流量净额', '投资活动现金流量净额', '筹资活动现金流量净额', '现金及现金等价物净增加额', '净资产增长率',
       '净利润增长率', '资产负债率变化', '金融资产增长率', '上市日期', '日期', '是否实施现金分红', '是否实施股票股利',
       '是否公积金转增股本', '相关股东前三个月内存在减持情形', '相关股东后三个月存在减持计划', '现金分红金额', '送股比例',
       '转增比例', '是否进行权益分派', '权益分派方案文本', '公司简称'],
      dtype='object')

# Law Article 13

## MEU_13_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 合并资产负债表、母公司资产负债表中本年末未分配利润均为正值且报告期内盈利，未进行现金分红或最近三年现金分红总额低于最近三年年均净利润30% |
| constraint | 应当在权益分派方案中披露：结合所处行业特点、发展阶段和自身经营模式、盈利水平、偿债能力、资金需求等因素，未进行现金分红或现金分红水平较低原因的说明 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2057 |
| completion_tokens | 11085 |

### 代码实现

In [3]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_10.csv')
date_columns = ["财务数据日期", "公告日期", "日期"]
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [4]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_13_1(df):
    '''
    检验MEU_13_1合规性: 
    subject: 上市公司
    condition: 合并及母公司资产负债表未分配利润均为正且报告期盈利, 且未分红或近三年分红低于年均净利30%
    constraint: 需在权益分派方案中披露: 结合所处行业特点、发展阶段和自身经营模式、盈利水平、偿债能力、资金需求等因素，未进行现金分红或现金分红水平较低原因的说明
    contextual_info: 只考虑上市后年报分红情况; "本年"理解为上一个最新的年报的数据; 最近三年理解为检查上市后的最近三年年报情况, 上市不足三年的取上市后所有年的年报情况
    '''
    df = df.copy()
    
    # 1. 标记责任主体（上市公司全为True）
    df['meu_13_1_subject'] = True

    # 2. 初始化标记列
    df['meu_13_1_condition'] = False
    df['meu_13_1_constraint'] = None

    # 预处理年报数据（年末数据）
    df['is_annual'] = df['财务数据日期'].apply(lambda x: x.month == 12 and x.day == 31)
    df['is_post_ipo'] = (df['公告日期'] > df['上市日期'])

    # 计算每个公司每个年报的三年指标（改进后的逻辑）
    def process_company(group):
        group = group.sort_values('财务数据日期', ascending=False)
        for idx, row in group.iterrows():
            current_date = row['财务数据日期']
            # 获取当前日期前的所有年报（包含当前）
            mask = group['财务数据日期'] <= current_date
            eligible_reports = group[mask]
            # 取最近三个年报（可能不足三个）
            recent_three = eligible_reports.head(3)
            
            # 计算分红总和与年均归属于上市公司股东的净利润
            total_dividend = recent_three['现金分红金额'].sum()
            total_net_income = recent_three['归属于上市公司股东的净利润'].sum()
            num_years = len(recent_three)
            
            group.loc[idx, '3yr_dividend'] = total_dividend
            group.loc[idx, '3yr_avg_net'] = total_net_income / num_years
        return group

    # 仅处理上市后年报数据
    annual_df = df[(df['is_annual']) & (df['is_post_ipo'])].copy()

    annual_df = annual_df.groupby('公司简称', group_keys=False).apply(process_company)
    # 使用merge确保保留原始数据
    df = df.merge(
        annual_df[['公司简称', '财务数据日期', '3yr_dividend', '3yr_avg_net']],
        on=['公司简称', '财务数据日期'],
        how='left'
    )
    
    # 计算触发条件（仅对年报数据）
    cond_a = df['合并报表未分配利润'] > 0
    cond_b = df['母公司报表未分配利润'] > 0
    cond_c = df['归属于上市公司股东的净利润'] > 0
    cond_d = (
        (~df['是否实施现金分红']) |
        (df['3yr_dividend'] < df['3yr_avg_net'] * 0.3)
    )
    df['meu_13_1_condition'] = df['is_annual'] & cond_a & cond_b & cond_c & cond_d

    # 3. 验证约束条件（LLM内容检查）
    mask = df['meu_13_1_subject'] & df['meu_13_1_condition']
    df.loc[mask, 'meu_13_1_constraint'] = df.loc[mask, '权益分派方案文本'].apply(
        lambda text: llm_content_check(
            text,
            "结合所处行业特点、发展阶段和自身经营模式、盈利水平、偿债能力、资金需求等因素，未进行现金分红或现金分红水平较低原因的说明"
        ) if pd.notnull(text) else False
    )

    # 清理临时列
    df.drop(['is_annual', 'is_post_ipo', '3yr_dividend', '3yr_avg_net'], axis=1, inplace=True, errors='ignore')

    return df

In [5]:
df = check_meu_13_1(df)
df

/var/folders/0l/pjlf4pl90rx7ldkq7jx18ny00000gn/T/ipykernel_10255/2260643506.py:48: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  annual_df = annual_df.groupby('公司简称', group_keys=False).apply(process_company)

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,相关股东后三个月存在减持计划,现金分红金额,送股比例,转增比例,是否进行权益分派,权益分派方案文本,公司简称,meu_13_1_subject,meu_13_1_condition,meu_13_1_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,False,0.0,0,0,False,[],曦祺电力,True,True,True
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,False,0.0,0,0,False,[],蔚珵食品,True,False,None
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,False,0.0,1,0,True,['留存未分配利润的预计用途以及收益情况'],蔚珵食品,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,True,True

In [6]:
df.to_csv("temp.csv", encoding='utf-8-sig', index=False)

In [7]:
df[df['meu_13_1_condition']==True][['日期', '归属于上市公司股东的净利润', '现金分红金额', '公司简称']]

             日期  归属于上市公司股东的净利润  现金分红金额  公司简称
3    2018-05-06   1.852620e+07     0.0  曦祺电力
7    2019-04-20   5.118393e+07     0.0  曦祺电力
19   2022-05-12   1.976009e+07     0.0  曦祺电力
23   2023-04-29   3.795464e+07     0.0  曦祺电力
27   2024-05-01   3.764807e+07     0.0  曦祺电力
...         ...            ...     ...   ...
6351 2021-05-16   2.003849e+07     0.0  昀珵交通
6371 2018-04-15   8.843535e+06     0.0  蔚珵食品
6379 2020-05-10   8.386960e+06     0.0  蔚珵食品
6383 2021-04-17   1.026874e+07     0.0  蔚珵食品
6399 2025-05-19   4.269576e+06     0.0  蔚珵食品

[689 rows x 4 columns]

---

## MEU_13_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 合并资产负债表、母公司资产负债表中本年末未分配利润均为正值且报告期内盈利，未进行现金分红或最近三年现金分红总额低于最近三年年均净利润30% |
| constraint | 应当在权益分派方案中披露：留存未分配利润的预计用途以及收益情况 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2034 |
| completion_tokens | 7261 |

### 代码实现

In [8]:
import pandas as pd
from utils.tool_for_agents import llm_content_check


def check_meu_13_2(df):
    '''
    检验MEU_13_2合规性: 
    subject: 上市公司
    condition: 合并及母公司资产负债表未分配利润均为正且报告期盈利, 且未分红或近三年分红低于年均净利30%
    constraint: 需在权益分派方案中披露: 留存未分配利润的预计用途以及收益情况
    contextual_info: 只考虑上市后年报分红情况; "本年"理解为上一个最新的年报的数据; 最近三年理解为检查上市后的最近三年年报情况, 上市不足三年的取上市后所有年的年报情况
    '''
    df = df.copy()
    
    # 1. 标记责任主体（上市公司全为True）
    df['meu_13_2_subject'] = True

    # 2. 初始化标记列
    df['meu_13_2_condition'] = False
    df['meu_13_2_constraint'] = None

    # 预处理年报数据（年末数据）
    df['is_annual'] = df['财务数据日期'].apply(lambda x: x.month == 12 and x.day == 31)
    df['is_post_ipo'] = (df['公告日期'] > df['上市日期'])

    # 计算每个公司每个年报的三年指标（改进后的逻辑）
    def process_company(group):
        group = group.sort_values('财务数据日期', ascending=False)
        for idx, row in group.iterrows():
            current_date = row['财务数据日期']
            # 获取当前日期前的所有年报（包含当前）
            mask = group['财务数据日期'] <= current_date
            eligible_reports = group[mask]
            # 取最近三个年报（可能不足三个）
            recent_three = eligible_reports.head(3)
            
            # 计算分红总和与年均归属于上市公司股东的净利润
            total_dividend = recent_three['现金分红金额'].sum()
            total_net_income = recent_three['归属于上市公司股东的净利润'].sum()
            num_years = len(recent_three)
            
            group.loc[idx, '3yr_dividend'] = total_dividend
            group.loc[idx, '3yr_avg_net'] = total_net_income / num_years
        return group

    # 仅处理上市后年报数据
    annual_df = df[(df['is_annual']) & (df['is_post_ipo'])].copy()

    annual_df = annual_df.groupby('公司简称', group_keys=False).apply(process_company)
    # 使用merge确保保留原始数据
    df = df.merge(
        annual_df[['公司简称', '财务数据日期', '3yr_dividend', '3yr_avg_net']],
        on=['公司简称', '财务数据日期'],
        how='left'
    )
    
    # 计算触发条件（仅对年报数据）
    cond_a = df['合并报表未分配利润'] > 0
    cond_b = df['母公司报表未分配利润'] > 0
    cond_c = df['归属于上市公司股东的净利润'] > 0
    cond_d = (
        (~df['是否实施现金分红']) |
        (df['3yr_dividend'] < df['3yr_avg_net'] * 0.3)
    )
    df['meu_13_2_condition'] = df['is_annual'] & cond_a & cond_b & cond_c & cond_d

    # 3. 验证约束条件（LLM内容检查）
    mask = df['meu_13_2_subject'] & df['meu_13_2_condition']
    df.loc[mask, 'meu_13_2_constraint'] = df.loc[mask, '权益分派方案文本'].apply(
        lambda text: llm_content_check(
            text,
            "留存未分配利润的预计用途以及收益情况"
        ) if pd.notnull(text) else False
    )

    # 清理临时列
    df.drop(['is_annual', 'is_post_ipo', '3yr_dividend', '3yr_avg_net'], axis=1, inplace=True, errors='ignore')

    return df

In [9]:
df = check_meu_13_2(df)
df

/var/folders/0l/pjlf4pl90rx7ldkq7jx18ny00000gn/T/ipykernel_10255/2094903079.py:49: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  annual_df = annual_df.groupby('公司简称', group_keys=False).apply(process_company)

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,转增比例,是否进行权益分派,权益分派方案文本,公司简称,meu_13_1_subject,meu_13_1_condition,meu_13_1_constraint,meu_13_2_subject,meu_13_2_condition,meu_13_2_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,0,False,[],曦祺电力,True,False,None,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,0,False,[],曦祺电力,True,False,None,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,0,False,[],曦祺电力,True,False,None,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,0,False,[],曦祺电力,True,True,True,True,True,True
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,0,False,[],曦祺电力,True,False,None,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,0,False,[],蔚珵食品,True,False,None,True,False,None
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,0,False,[],蔚珵食品,True,False,None,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,0,False,[],蔚珵食品,True,False,None,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,0,True,['留存未分配利润的预计用途以及收益情况'],蔚珵食品,True,False,None,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,0,False,[],蔚珵食品,True,True,True,True,True,True

---

## MEU_13_3


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 合并资产负债表、母公司资产负债表中本年末未分配利润均为正值且报告期内盈利，未进行现金分红或最近三年现金分红总额低于最近三年年均净利润30% |
| constraint | 应当在权益分派方案中披露：公司在相应期间是否按照中国证券监督管理委员会相关规定为中小股东参与现金分红决策提供了便利 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2043 |
| completion_tokens | 8462 |

### 代码实现

In [10]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_13_3(df):
    '''
    验证上市公司在满足特定利润条件和分红限制时是否披露中小股东参与决策便利
    "subject": "上市公司",
    "condition": "合并及母公司未分配利润为正+报告期盈利+未分红或三年分红不足净利润30%",
    "constraint": "需在权益分派方案中披露中小股东参与决策便利条款"
    '''
    
    # 初始化合规标记列
    df['meu_13_3_subject'] = True  # 所有行默认符合主体要求
    df['meu_13_3_condition'] = False
    df['meu_13_3_constraint'] = None

    # 预处理财务日期并筛选年报数据
    df['财务数据日期'] = pd.to_datetime(df['财务数据日期'])
    annual_mask = df['财务数据日期'].dt.month == 12
    annual_df = df[annual_mask].copy()

    if not annual_df.empty:
        # 按公司分组计算三年滚动指标
        annual_df = annual_df.sort_values(by=['公司简称', '财务数据日期'])
        
        # 计算三年现金分红总和
        annual_df['cash_div_3yr'] = annual_df.groupby('公司简称')['现金分红金额']\
            .transform(lambda s: s.rolling(3, min_periods=3).sum())
        
        # 计算三年平均归属于上市公司股东的净利润
        annual_df['net_profit_3yr_avg'] = annual_df.groupby('公司简称')['归属于上市公司股东的净利润']\
            .transform(lambda s: s.rolling(3, min_periods=3).sum() / 3)
        
        # 将计算结果合并回原数据框
        df = df.merge(
            annual_df[['cash_div_3yr', 'net_profit_3yr_avg']],
            how='left', left_index=True, right_index=True
        )

        # 条件验证逻辑
        profit_condition = (
            (df['合并报表未分配利润'] > 0) &
            (df['母公司报表未分配利润'] > 0) &
            (df['归属于上市公司股东的净利润'] > 0)
        )
        
        dividend_condition = (
            (~df['是否实施现金分红']) |  # 未分红情形
            (df['cash_div_3yr'] < df['net_profit_3yr_avg'] * 0.3)  # 分红不足情形
        )
        
        # 综合条件标记（仅限年报数据）
        df['meu_13_3_condition'] = annual_mask & profit_condition & dividend_condition
        
        # 约束条件验证（仅当满足主体和条件时触发）
        need_check_mask = df['meu_13_3_subject'] & df['meu_13_3_condition']
        df.loc[need_check_mask, 'meu_13_3_constraint'] = df.loc[need_check_mask, '权益分派方案文本'].apply(
            lambda text: llm_content_check(
                text, 
                "公司在相应期间是否按照中国证券监督管理委员会相关规定为中小股东参与现金分红决策提供了便利"
            )
        )

    return df

In [11]:
df = check_meu_13_3(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,meu_13_1_condition,meu_13_1_constraint,meu_13_2_subject,meu_13_2_condition,meu_13_2_constraint,meu_13_3_subject,meu_13_3_condition,meu_13_3_constraint,cash_div_3yr,net_profit_3yr_avg
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,False,None,True,False,None,True,False,None,NaN,NaN
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,False,None,True,False,None,True,False,None,NaN,NaN
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,False,None,True,False,None,True,False,None,NaN,NaN
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,True,True,True,True,True,True,True,True,NaN,NaN
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,False,None,True,False,None,True,False,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,False,None,True,False,None,True,False,None,0.0,-1.210711e+06
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,False,None,True,False,None,True,False,None,NaN,NaN
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,False,None,True,False,None,True,False,None,NaN,NaN
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,False,None,True,False,None,True,False,None,NaN,NaN
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,True,True,True,True,True,True,True,True,0.0,6.625790e+05

---

## MEU_13_4


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 合并资产负债表、母公司资产负债表中本年末未分配利润均为正值且报告期内盈利，未进行现金分红或最近三年现金分红总额低于最近三年年均净利润30% |
| constraint | 应当在权益分派方案中披露：公司为增强投资者回报水平拟采取的措施 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2033 |
| completion_tokens | 9013 |

### 代码实现

In [12]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_13_4(df):
    '''
    检验MEU_13_4合规性: 
    subject: 上市公司
    condition: 合并及母公司资产负债表未分配利润均为正且报告期盈利, 且未分红或近三年分红低于年均净利30%
    constraint: 需在权益分派方案中披露: 公司为增强投资者回报水平拟采取的措施
    contextual_info: 只考虑上市后年报分红情况; "本年"理解为上一个最新的年报的数据; 最近三年理解为检查上市后的最近三年年报情况, 上市不足三年的取上市后所有年的年报情况
    '''
    df = df.copy()
    
    # 1. 标记责任主体（上市公司全为True）
    df['meu_13_4_subject'] = True

    # 2. 初始化标记列
    df['meu_13_4_condition'] = False
    df['meu_13_4_constraint'] = None

    # 预处理年报数据（年末数据）
    df['is_annual'] = df['财务数据日期'].apply(lambda x: x.month == 12 and x.day == 31)
    df['is_post_ipo'] = (df['公告日期'] > df['上市日期'])

    # 计算每个公司每个年报的三年指标（改进后的逻辑）
    def process_company(group):
        group = group.sort_values('财务数据日期', ascending=False)
        for idx, row in group.iterrows():
            current_date = row['财务数据日期']
            # 获取当前日期前的所有年报（包含当前）
            mask = group['财务数据日期'] <= current_date
            eligible_reports = group[mask]
            # 取最近三个年报（可能不足三个）
            recent_three = eligible_reports.head(3)
            
            # 计算分红总和与年均净利润
            total_dividend = recent_three['现金分红金额'].sum()
            total_net_income = recent_three['归属于上市公司股东的净利润'].sum()
            num_years = len(recent_three)
            
            group.loc[idx, '3yr_dividend'] = total_dividend
            group.loc[idx, '3yr_avg_net'] = total_net_income / num_years
        return group

    # 仅处理上市后年报数据
    annual_df = df[(df['is_annual']) & (df['is_post_ipo'])].copy()

    annual_df = annual_df.groupby('公司简称', group_keys=False).apply(process_company)
    # 使用merge确保保留原始数据
    df = df.merge(
        annual_df[['公司简称', '财务数据日期', '3yr_dividend', '3yr_avg_net']],
        on=['公司简称', '财务数据日期'],
        how='left'
    )
    
    # 计算触发条件（仅对年报数据）
    cond_a = df['合并报表未分配利润'] > 0
    cond_b = df['母公司报表未分配利润'] > 0
    cond_c = df['归属于上市公司股东的净利润'] > 0
    cond_d = (
        (~df['是否实施现金分红']) |
        (df['3yr_dividend'] < df['3yr_avg_net'] * 0.3)
    )
    df['meu_13_4_condition'] = df['is_annual'] & cond_a & cond_b & cond_c & cond_d

    # 3. 验证约束条件（LLM内容检查）
    mask = df['meu_13_4_subject'] & df['meu_13_4_condition']
    df.loc[mask, 'meu_13_4_constraint'] = df.loc[mask, '权益分派方案文本'].apply(
        lambda text: llm_content_check(
            text,
            "公司为增强投资者回报水平拟采取的措施"
        ) if pd.notnull(text) else False
    )

    # 清理临时列
    df.drop(['is_annual', 'is_post_ipo', '3yr_dividend', '3yr_avg_net'], axis=1, inplace=True, errors='ignore')

    return df

In [13]:
df = check_meu_13_4(df)
df

/var/folders/0l/pjlf4pl90rx7ldkq7jx18ny00000gn/T/ipykernel_10255/314452623.py:48: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  annual_df = annual_df.groupby('公司简称', group_keys=False).apply(process_company)

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,meu_13_2_condition,meu_13_2_constraint,meu_13_3_subject,meu_13_3_condition,meu_13_3_constraint,cash_div_3yr,net_profit_3yr_avg,meu_13_4_subject,meu_13_4_condition,meu_13_4_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,False,None,True,False,None,NaN,NaN,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,False,None,True,False,None,NaN,NaN,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,False,None,True,False,None,NaN,NaN,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,True,True,True,True,True,NaN,NaN,True,True,True
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,False,None,True,False,None,NaN,NaN,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,False,None,True,False,None,0.0,-1.210711e+06,True,False,None
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,False,None,True,False,None,NaN,NaN,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,False,None,True,False,None,NaN,NaN,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,False,None,True,False,None,NaN,NaN,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,True,True,True,True,True,0.0,6.625790e+05,True,True,True

---

## MEU_13_5


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 母公司资产负债表中未分配利润为负值但合并资产负债表中未分配利润为正值 |
| constraint | 应当在权益分派相关公告中披露上市公司控股子公司向母公司实施利润分配的情况 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2016 |
| completion_tokens | 5512 |

### 代码实现

In [14]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_13_5(df):
    '''
    检查MEU_13_5合规性：
    - subject: 上市公司（所有记录默认符合）
    - condition: 母公司未分配利润<0且合并报表未分配利润>0
    - constraint: 权益分派公告需披露子公司向母公司利润分配情况
    '''
    
    # 初始化合规标记列
    df['meu_13_5_subject'] = True  # 所有记录主体均为上市公司
    df['meu_13_5_condition'] = False
    df['meu_13_5_constraint'] = None  # 默认视为满足约束
    
    # 标记条件满足情况
    # 条件判断：母公司未分配利润为负且合并报表为正
    valid_condition = (df['母公司报表未分配利润'] < 0) & (df['合并报表未分配利润'] > 0)
    df['meu_13_5_condition'] = valid_condition
    
    # 约束条件处理
    target_description = "上市公司控股子公司向母公司实施利润分配的情况"
    # 仅当同时满足以下情况需要检查：1.条件成立 2.实际进行权益分派
    need_check_mask = valid_condition & df['是否进行权益分派']
    
    # 使用LLM检查分派方案文本
    df.loc[need_check_mask, 'meu_13_5_constraint'] = df.loc[need_check_mask, '权益分派方案文本'].apply(
        lambda text: llm_content_check(text, target_description) if pd.notnull(text) else False
    )
    
    return df

In [15]:
df = check_meu_13_5(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,meu_13_3_condition,meu_13_3_constraint,cash_div_3yr,net_profit_3yr_avg,meu_13_4_subject,meu_13_4_condition,meu_13_4_constraint,meu_13_5_subject,meu_13_5_condition,meu_13_5_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,False,None,NaN,NaN,True,False,None,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,False,None,NaN,NaN,True,False,None,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,False,None,NaN,NaN,True,False,None,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,True,True,NaN,NaN,True,True,True,True,False,None
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,False,None,NaN,NaN,True,False,None,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,False,None,0.0,-1.210711e+06,True,False,None,True,False,None
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,False,None,NaN,NaN,True,False,None,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,False,None,NaN,NaN,True,False,None,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,False,None,NaN,NaN,True,False,None,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,True,True,0.0,6.625790e+05,True,True,True,True,False,None

---

## MEU_13_6


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 母公司资产负债表中未分配利润为负值但合并资产负债表中未分配利润为正值 |
| constraint | 应当在权益分派相关公告中披露公司为增强投资者回报水平拟采取的措施 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2016 |
| completion_tokens | 3050 |

### 代码实现

In [16]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_13_6(df):
    '''
    验证上市公司在母公司未分配利润为负但合并报表为正时，是否披露增强回报措施
    
    "subject": "上市公司",
    "condition": "母公司资产负债表中未分配利润为负值但合并资产负债表中未分配利润为正值",
    "constraint": "应当在权益分派相关公告中披露公司为增强投资者回报水平拟采取的措施"
    '''
    
    # 初始化所有标记列
    df['meu_13_6_subject'] = True  # 所有记录主体都是上市公司
    df['meu_13_6_condition'] = False
    df['meu_13_6_constraint'] = None
    
    # 1. 验证condition条件
    parent_profit_negative = df['母公司报表未分配利润'] < 0
    consolidated_profit_positive = df['合并报表未分配利润'] > 0
    condition_met = parent_profit_negative & consolidated_profit_positive
    df.loc[condition_met, 'meu_13_6_condition'] = True
    
    # 2. 验证constraint约束（仅当condition满足时检查）
    if condition_met.any():
        # 获取需要检查的公告文本
        target_desc = "为增强投资者回报水平拟采取的措施"
        
        # 对满足条件的行进行内容检查
        constrained_mask = condition_met & df['权益分派方案文本'].notna()
        df.loc[constrained_mask, 'meu_13_6_constraint'] = df.loc[constrained_mask, '权益分派方案文本'].apply(
            lambda text: llm_content_check(text, target_desc)
        )
        
        # 处理文本为空的情况（视为未披露）
        df.loc[condition_met & df['权益分派方案文本'].isna(), 'meu_13_6_constraint'] = False
    
    return df

In [17]:
df = check_meu_13_6(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,net_profit_3yr_avg,meu_13_4_subject,meu_13_4_condition,meu_13_4_constraint,meu_13_5_subject,meu_13_5_condition,meu_13_5_constraint,meu_13_6_subject,meu_13_6_condition,meu_13_6_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,NaN,True,False,None,True,False,None,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,NaN,True,False,None,True,False,None,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,NaN,True,False,None,True,False,None,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,NaN,True,True,True,True,False,None,True,False,None
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,NaN,True,False,None,True,False,None,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,-1.210711e+06,True,False,None,True,False,None,True,False,None
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,NaN,True,False,None,True,False,None,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,NaN,True,False,None,True,False,None,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,NaN,True,False,None,True,False,None,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,6.625790e+05,True,True,True,True,False,None,True,False,None

---

# Law Article 14

## MEU_14_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 合并资产负债表、母公司资产负债表中本年末未分配利润均为正值且报告期内盈利，且最近连续两个会计年度经审计的下列财务报表项目金额合计占总资产的50%以上：交易性金融资产、衍生金融资产（套期保值工具除外）、债权投资、其他债权投资、其他权益工具投资、其他非流动金融资产、其他流动资产（待抵扣增值税、预缴税费、合同取得成本等与经营活动相关的资产除外），且未进行现金分红或者现金分红总额低于当年净利润50% |
| constraint | 应当在权益分派方案中结合前述财务报表列报项目的具体情况说明现金分红方案确定的依据及未来增强投资者回报的规划 |
| contextual_info | 财务报表项目具体范围包含：交易性金融资产、衍生金融资产（套期保值工具除外）、债权投资、其他债权投资、其他权益工具投资、其他非流动金融资产、其他流动资产（待抵扣增值税、预缴税费、合同取得成本等与经营活动相关的资产除外） |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2173 |
| completion_tokens | 10263 |

### 代码实现

In [18]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_14_1(df):
    '''
    验证上市公司在特定财务条件下的现金分红方案披露合规性
    "subject": "上市公司", 
    "condition": "合并及母公司未分配利润为正+连续两年金融资产占比超50%+现金分红不足净利润50%", 
    "constraint": "需在权益分派方案中说明依据及回报规划", 
    "contextual_info": "金融资产范围包含交易性金融资产等7项（特定项目除外）"
    '''
    # 初始化标记列
    df['meu_14_1_subject'] = True  # 所有行均为上市公司
    df['meu_14_1_condition'] = False
    df['meu_14_1_constraint'] = None

    # 预处理：按公司分组并计算历史数据
    df_sorted = df.sort_values(['公司简称', '财务数据日期'])
    grouped = df_sorted.groupby('公司简称')

    # 计算前一年度财务指标
    financial_columns = ['总资产', '交易性金融资产', '衍生金融资产', '债权投资', '其他债权投资',
                        '其他权益工具投资', '其他非流动金融资产', '其他流动资产']
    for col in financial_columns:
        df_sorted[f'prev_{col}'] = grouped[col].shift(1)

    # 合并回原始索引顺序
    df = df_sorted.reset_index(drop=True).reindex(df.index)

    # 条件验证逻辑
    # 1. 基础财务条件
    is_annual = df['财务数据日期'].dt.month == 12
    profit_condition = (
        (df['合并报表未分配利润'] > 0) &
        (df['母公司报表未分配利润'] > 0) &
        (df['归属于上市公司股东的净利润'] > 0)
    )

    # 2. 金融资产占比条件
    current_fa = (
        df['交易性金融资产'] + 
        df['衍生金融资产'] +  # 假设已排除套期工具
        df['债权投资'] +
        df['其他债权投资'] +
        df['其他权益工具投资'] +
        df['其他非流动金融资产'] +
        df['其他流动资产']  # 假设已排除特定项目
    )
    prev_fa = (
        df['prev_交易性金融资产'] + 
        df['prev_衍生金融资产'] +
        df['prev_债权投资'] +
        df['prev_其他债权投资'] +
        df['prev_其他权益工具投资'] +
        df['prev_其他非流动金融资产'] +
        df['prev_其他流动资产']
    )
    fa_ratio_condition = (
        (current_fa / df['总资产'] >= 0.5) &
        (prev_fa / df['prev_总资产'] >= 0.5) &
        df['prev_总资产'].notna()
    )

    # 3. 现金分红条件
    dividend_condition = (
        ~df['是否实施现金分红'] | 
        (df['现金分红金额'] < df['归属于上市公司股东的净利润'] * 0.5)
    )

    # 综合条件判断
    valid_condition = (
        is_annual &
        profit_condition &
        fa_ratio_condition &
        dividend_condition
    )
    df['meu_14_1_condition'] = valid_condition

    # 约束条件验证
    constraint_desc = "结合前述财务报表列报项目的具体情况说明现金分红方案确定的依据及未来增强投资者回报的规划"
    need_check = valid_condition & df['是否进行权益分派']
    df.loc[need_check, 'meu_14_1_constraint'] = df.loc[need_check, '权益分派方案文本'].apply(
        lambda x: llm_content_check(x, constraint_desc) if pd.notnull(x) else False
    )


    return df

In [19]:
df = check_meu_14_1(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,meu_14_1_condition,meu_14_1_constraint,prev_总资产,prev_交易性金融资产,prev_衍生金融资产,prev_债权投资,prev_其他债权投资,prev_其他权益工具投资,prev_其他非流动金融资产,prev_其他流动资产
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.384595e+08,5.967386e+07,1.787856e+08,0.250247,1.534606e+07,...,False,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.123215e+08,4.807545e+07,1.642460e+08,0.226428,1.422379e+07,...,False,None,2.384595e+08,1.534606e+07,1.491881e+06,5.408492e+07,1.693357e+06,4.587322e+06,1.201637e+07,2.262443e+07
2,2017-09-30,季报,2017-10-27,无保留意见,False,2.217586e+08,4.934872e+07,1.724099e+08,0.222534,1.443740e+07,...,False,None,2.123215e+08,1.422379e+07,1.235171e+06,4.964255e+07,1.435106e+06,4.134532e+06,1.034152e+07,2.036408e+07
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.333176e+08,5.725981e+07,1.760578e+08,0.245416,1.669366e+07,...,False,None,2.217586e+08,1.443740e+07,1.534444e+06,5.253453e+07,1.539087e+06,4.636707e+06,1.103962e+07,2.263050e+07
4,2018-03-31,季报,2018-04-30,无保留意见,False,2.723056e+08,6.839593e+07,2.039096e+08,0.251173,1.812854e+07,...,False,None,2.333176e+08,1.669366e+07,1.526138e+06,6.142017e+07,1.784780e+06,4.824573e+06,1.323561e+07,2.499319e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,6.078571e+08,2.442760e+08,3.635811e+08,0.401864,2.407451e+07,...,False,None,6.360718e+08,2.866849e+07,4.531638e+03,2.325034e+02,1.172265e+08,1.912116e+06,1.311812e+07,1.602517e+07
6396,2024-03-31,季报,2024-04-30,非标准无保留意见,False,6.964087e+08,3.119972e+08,3.844115e+08,0.448009,2.826385e+07,...,False,None,6.078571e+08,2.407451e+07,4.817030e+03,1.879486e+02,1.206403e+08,1.743518e+06,1.213175e+07,1.454014e+07
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.592984e+08,4.373654e+08,4.219330e+08,0.508980,3.399481e+07,...,False,None,6.964087e+08,2.826385e+07,4.516106e+03,2.327558e+02,1.408130e+08,1.857506e+06,1.241809e+07,1.482556e+07
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.401049e+08,5.266185e+08,4.134865e+08,0.560170,3.892565e+07,...,False,None,8.592984e+08,3.399481e+07,6.010863e+03,2.844315e+02,1.704016e+08,2.589621e+06,1.636778e+07,1.857244e+07
6399,2024-12-31,年报,2025-03-30,无保留意见,False,1.153727e+09,7.256438e+08,4.280837e+08,0.628956,4.518259e+07,...,False,None,9.401049e+08,3.892565e+07,6.761996e+03,3.459446e+02,1.881599e+08,2.940102e+06,1.874946e+07,2.011653e+07

In [20]:

df[df['meu_14_1_condition']==True]

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,meu_14_1_condition,meu_14_1_constraint,prev_总资产,prev_交易性金融资产,prev_衍生金融资产,prev_债权投资,prev_其他债权投资,prev_其他权益工具投资,prev_其他非流动金融资产,prev_其他流动资产
99,2017-12-31,年报,2018-03-30,无保留意见,False,3.264901e+08,1.055597e+08,2.209304e+08,0.323317,6.518708e+07,...,True,None,3.066886e+08,5.606952e+07,1.448904e-14,5.447106e+07,1.557206e+01,8.206966e+06,3.145424e+07,3.878689e+07
103,2018-12-31,年报,2019-03-30,无保留意见,True,4.047191e+08,1.461197e+08,2.585994e+08,0.361040,7.800486e+07,...,True,None,3.418350e+08,6.347207e+07,1.475986e-14,6.708913e+07,2.020227e+01,1.050462e+07,3.662114e+07,4.767776e+07
119,2022-12-31,年报,2023-03-30,非标准无保留意见,False,1.432347e+09,8.926161e+08,5.397309e+08,0.623184,2.984721e+08,...,True,None,1.360843e+09,2.239106e+08,5.287782e-14,2.424580e+08,7.461732e+01,3.779721e+07,1.368891e+08,1.736965e+08
127,2024-12-31,年报,2025-03-30,无保留意见,False,1.802407e+09,1.026765e+09,7.756423e+08,0.569663,3.097408e+08,...,True,None,1.948698e+09,3.938259e+08,9.634827e-14,3.396100e+08,1.048333e+02,6.048580e+07,2.104439e+08,2.543603e+08
131,2017-12-31,年报,2018-03-30,无保留意见,False,3.850365e+08,1.783942e+08,2.066423e+08,0.463318,1.479544e+07,...,True,None,3.191787e+08,1.360112e+07,1.119339e-08,5.487696e+06,3.559938e+07,1.989563e+05,1.281364e+08,7.143654e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6339,2017-12-31,年报,2018-03-30,无保留意见,False,3.985801e+08,1.724320e+08,2.261481e+08,0.432616,2.497632e+07,...,True,None,3.913460e+08,2.743952e+07,1.018832e+02,2.698966e+07,9.656028e+06,6.210374e+07,4.796754e+05,1.282557e+08
6343,2018-12-31,年报,2019-03-30,无保留意见,True,4.879777e+08,2.847688e+08,2.032089e+08,0.583569,3.643996e+07,...,True,None,4.848394e+08,3.270094e+07,1.300586e+02,3.308497e+07,1.433939e+07,7.917222e+07,5.936139e+05,1.702856e+08
6359,2022-12-31,年报,2023-03-30,无保留意见,False,1.094154e+09,6.462738e+08,4.478806e+08,0.590661,7.106197e+07,...,True,None,1.497429e+09,8.953351e+07,4.065518e+02,9.927416e+07,3.867719e+07,2.479125e+08,1.870379e+06,4.839532e+08
6363,2023-12-31,年报,2024-03-30,无保留意见,False,1.307372e+09,7.334593e+08,5.739129e+08,0.561018,8.671247e+07,...,True,None,1.587042e+09,1.042872e+08,3.944658e+02,9.849439e+07,4.103497e+07,2.393906e+08,1.977913e+06,5.383480e+08
6367,2024-12-31,年报,2025-03-30,非标准无保留意见,False,1.572336e+09,8.740600e+08,6.982757e+08,0.555899,9.658610e+07,...,True,None,1.690659e+09,1.119962e+08,4.501110e+02,1.040192e+08,4.718585e+07,2.723125e+08,2.121350e+06,5.925213e+08

---

# Law Article 15

## MEU_15_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 权益分派方案中现金分红的金额达到或者超过当期净利润的100%且达到或者超过当期末未分配利润的50% |
| constraint | 应当同时披露是否影响偿债能力、过去十二个月内是否使用过募集资金补充流动资金以及未来十二个月内是否计划使用募集资金补充流动资金等内容 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2041 |
| completion_tokens | 5042 |

### 代码实现

In [21]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_15_1(df):
    '''
    验证上市公司在超高比例分红时的信息披露合规性
    subject: 上市公司
    condition: 现金分红≥净利润100%且≥未分配利润50%
    constraint: 需披露偿债影响、募集资金使用情况
    '''
    
    # 初始化合规标记列
    df['meu_15_1_subject'] = True  # 所有记录主体均为上市公司
    df['meu_15_1_condition'] = False
    df['meu_15_1_constraint'] = None
    

    # 条件验证：现金分红达标
    cash_condition = (
        (df['现金分红金额'] >= df['归属于上市公司股东的净利润']) & 
        (df['现金分红金额'] >= df['合并报表未分配利润'] * 0.5)
    )
    df.loc[cash_condition, 'meu_15_1_condition'] = True
    
    # 约束验证：信息披露完整性
    def check_disclosure(text):
        if pd.isna(text):
            return False
        return (
            llm_content_check(text, "是否影响偿债能力") &
            llm_content_check(text, "过去十二个月内是否使用过募集资金补充流动资金") &
            llm_content_check(text, "未来十二个月内是否计划使用募集资金补充流动资金")
        )
    
    df.loc[cash_condition, 'meu_15_1_constraint'] = df['权益分派方案文本'].apply(check_disclosure)
    
    
    return df

In [22]:
df = check_meu_15_1(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,prev_交易性金融资产,prev_衍生金融资产,prev_债权投资,prev_其他债权投资,prev_其他权益工具投资,prev_其他非流动金融资产,prev_其他流动资产,meu_15_1_subject,meu_15_1_condition,meu_15_1_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.384595e+08,5.967386e+07,1.787856e+08,0.250247,1.534606e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.123215e+08,4.807545e+07,1.642460e+08,0.226428,1.422379e+07,...,1.534606e+07,1.491881e+06,5.408492e+07,1.693357e+06,4.587322e+06,1.201637e+07,2.262443e+07,True,True,True
2,2017-09-30,季报,2017-10-27,无保留意见,False,2.217586e+08,4.934872e+07,1.724099e+08,0.222534,1.443740e+07,...,1.422379e+07,1.235171e+06,4.964255e+07,1.435106e+06,4.134532e+06,1.034152e+07,2.036408e+07,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.333176e+08,5.725981e+07,1.760578e+08,0.245416,1.669366e+07,...,1.443740e+07,1.534444e+06,5.253453e+07,1.539087e+06,4.636707e+06,1.103962e+07,2.263050e+07,True,False,None
4,2018-03-31,季报,2018-04-30,无保留意见,False,2.723056e+08,6.839593e+07,2.039096e+08,0.251173,1.812854e+07,...,1.669366e+07,1.526138e+06,6.142017e+07,1.784780e+06,4.824573e+06,1.323561e+07,2.499319e+07,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,6.078571e+08,2.442760e+08,3.635811e+08,0.401864,2.407451e+07,...,2.866849e+07,4.531638e+03,2.325034e+02,1.172265e+08,1.912116e+06,1.311812e+07,1.602517e+07,True,False,None
6396,2024-03-31,季报,2024-04-30,非标准无保留意见,False,6.964087e+08,3.119972e+08,3.844115e+08,0.448009,2.826385e+07,...,2.407451e+07,4.817030e+03,1.879486e+02,1.206403e+08,1.743518e+06,1.213175e+07,1.454014e+07,True,True,True
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.592984e+08,4.373654e+08,4.219330e+08,0.508980,3.399481e+07,...,2.826385e+07,4.516106e+03,2.327558e+02,1.408130e+08,1.857506e+06,1.241809e+07,1.482556e+07,True,True,True
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.401049e+08,5.266185e+08,4.134865e+08,0.560170,3.892565e+07,...,3.399481e+07,6.010863e+03,2.844315e+02,1.704016e+08,2.589621e+06,1.636778e+07,1.857244e+07,True,True,True
6399,2024-12-31,年报,2025-03-30,无保留意见,False,1.153727e+09,7.256438e+08,4.280837e+08,0.628956,4.518259e+07,...,3.892565e+07,6.761996e+03,3.459446e+02,1.881599e+08,2.940102e+06,1.874946e+07,2.011653e+07,True,True,True

---

## MEU_15_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 最近一个会计年度的财务会计报告被出具非无保留意见的审计报告或者带与持续经营相关的重大不确定性段落的无保留意见的审计报告，且实施现金分红的 |
| constraint | 应当根据公司盈利能力、融资能力及其成本、偿债能力及现金流等情况披露现金分红方案的合理性，是否导致公司营运资金不足或者影响公司正常生产经营 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2052 |
| completion_tokens | 4557 |

### 代码实现

In [23]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_15_2(df):
    '''
    合规性检验函数：MEU_15_2
    "subject": "上市公司",
    "condition": "最近一个会计年度的财务会计报告被出具非无保留意见的审计报告或者带与持续经营相关的重大不确定性段落的无保留意见的审计报告，且实施现金分红的",
    "constraint": "应当根据公司盈利能力、融资能力及其成本、偿债能力及现金流等情况披露现金分红方案的合理性，是否导致公司营运资金不足或者影响公司正常生产经营"
    '''

    # 初始化标记列
    df['meu_15_2_subject'] = True  # 所有行均为上市公司
    df['meu_15_2_condition'] = False
    df['meu_15_2_constraint'] = None 

    # 标记条件1：审计意见类型
    audit_condition = df['审计意见'].isin(['保留意见', '非标准无保留意见'])
    # 标记条件2：实施现金分红
    dividend_condition = df['是否实施现金分红']
    # 合并条件
    valid_condition = audit_condition & dividend_condition
    df['meu_15_2_condition'] = valid_condition

    # 标记约束（仅当满足主体和条件时检查）
    constraint_description = "根据公司盈利能力、融资能力及其成本、偿债能力及现金流等情况披露现金分红方案的合理性，是否导致公司营运资金不足或者影响公司正常生产经营"
    mask = df['meu_15_2_subject'] & df['meu_15_2_condition']
    
    # 对满足条件的行进行内容检查
    df.loc[mask, 'meu_15_2_constraint'] = df.loc[mask].apply(
        lambda row: llm_content_check(row['权益分派方案文本'], constraint_description) if pd.notna(row['权益分派方案文本']) else False,
        axis=1
    )

    return df

In [24]:
df = check_meu_15_2(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,prev_其他债权投资,prev_其他权益工具投资,prev_其他非流动金融资产,prev_其他流动资产,meu_15_1_subject,meu_15_1_condition,meu_15_1_constraint,meu_15_2_subject,meu_15_2_condition,meu_15_2_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.384595e+08,5.967386e+07,1.787856e+08,0.250247,1.534606e+07,...,NaN,NaN,NaN,NaN,True,True,True,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.123215e+08,4.807545e+07,1.642460e+08,0.226428,1.422379e+07,...,1.693357e+06,4.587322e+06,1.201637e+07,2.262443e+07,True,True,True,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,2.217586e+08,4.934872e+07,1.724099e+08,0.222534,1.443740e+07,...,1.435106e+06,4.134532e+06,1.034152e+07,2.036408e+07,True,False,None,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.333176e+08,5.725981e+07,1.760578e+08,0.245416,1.669366e+07,...,1.539087e+06,4.636707e+06,1.103962e+07,2.263050e+07,True,False,None,True,False,None
4,2018-03-31,季报,2018-04-30,无保留意见,False,2.723056e+08,6.839593e+07,2.039096e+08,0.251173,1.812854e+07,...,1.784780e+06,4.824573e+06,1.323561e+07,2.499319e+07,True,False,None,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,6.078571e+08,2.442760e+08,3.635811e+08,0.401864,2.407451e+07,...,1.172265e+08,1.912116e+06,1.311812e+07,1.602517e+07,True,False,None,True,False,None
6396,2024-03-31,季报,2024-04-30,非标准无保留意见,False,6.964087e+08,3.119972e+08,3.844115e+08,0.448009,2.826385e+07,...,1.206403e+08,1.743518e+06,1.213175e+07,1.454014e+07,True,True,True,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.592984e+08,4.373654e+08,4.219330e+08,0.508980,3.399481e+07,...,1.408130e+08,1.857506e+06,1.241809e+07,1.482556e+07,True,True,True,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.401049e+08,5.266185e+08,4.134865e+08,0.560170,3.892565e+07,...,1.704016e+08,2.589621e+06,1.636778e+07,1.857244e+07,True,True,True,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,1.153727e+09,7.256438e+08,4.280837e+08,0.628956,4.518259e+07,...,1.881599e+08,2.940102e+06,1.874946e+07,2.011653e+07,True,True,True,True,False,None

---

## MEU_15_3


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 报告期末资产负债率超过80%且当期经营活动产生的现金流量净额为负，且现金分红金额超过当期净利润50%的 |
| constraint | 应当根据公司盈利能力、融资能力及其成本、偿债能力及现金流等情况披露现金分红方案的合理性，是否导致公司营运资金不足或者影响公司正常生产经营 |
| contextual_info | nan |
| note | nan |
| relation | nan |
| target | nan |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2040 |
| completion_tokens | 3297 |

### 代码实现

In [25]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_15_3(df):
    '''
    验证MEU_15_3合规性：
    "subject": "上市公司",
    "condition": "报告期末资产负债率超过80%且当期经营活动产生的现金流量净额为负，且现金分红金额超过当期净利润50%的",
    "constraint": "应当根据公司盈利能力、融资能力及其成本、偿债能力及现金流等情况披露现金分红方案的合理性，是否导致公司营运资金不足或者影响公司正常生产经营"
    '''
    
    # 初始化标记列
    df['meu_15_3_subject'] = True  # 所有记录主体均为上市公司
    df['meu_15_3_condition'] = False
    df['meu_15_3_constraint'] = None


    # 1. 验证condition条件
    cond_leverage = df['资产负债率'] > 0.8  # 资产负债率超过80%
    cond_cashflow = df['经营活动现金流量净额'] < 0  # 经营活动现金流为负
    cond_dividend = df['现金分红金额'] > (df['归属于上市公司股东的净利润'] * 0.5)  # 分红超归属于上市公司股东的净利润50%
    
    valid_condition = cond_leverage & cond_cashflow & cond_dividend
    df.loc[valid_condition, 'meu_15_3_condition'] = True

    # 2. 验证constraint条件（仅当condition满足时检查）
    constraint_desc = '''披露现金分红方案的合理性，是否导致公司营运资金不足或者影响公司正常生产经营，
                         包括对公司盈利能力、融资能力及其成本、偿债能力及现金流等情况的说明'''
    
    # 仅对触发条件的记录进行内容检查
    mask = valid_condition & df['是否实施现金分红']
    df.loc[mask, 'meu_15_3_constraint'] = df[mask].apply(
        lambda x: llm_content_check(x['权益分派方案文本'], constraint_desc), 
        axis=1
    )

    return df

In [26]:
df = check_meu_15_3(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,prev_其他流动资产,meu_15_1_subject,meu_15_1_condition,meu_15_1_constraint,meu_15_2_subject,meu_15_2_condition,meu_15_2_constraint,meu_15_3_subject,meu_15_3_condition,meu_15_3_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.384595e+08,5.967386e+07,1.787856e+08,0.250247,1.534606e+07,...,NaN,True,True,True,True,False,None,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.123215e+08,4.807545e+07,1.642460e+08,0.226428,1.422379e+07,...,2.262443e+07,True,True,True,True,False,None,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,2.217586e+08,4.934872e+07,1.724099e+08,0.222534,1.443740e+07,...,2.036408e+07,True,False,None,True,False,None,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.333176e+08,5.725981e+07,1.760578e+08,0.245416,1.669366e+07,...,2.263050e+07,True,False,None,True,False,None,True,False,None
4,2018-03-31,季报,2018-04-30,无保留意见,False,2.723056e+08,6.839593e+07,2.039096e+08,0.251173,1.812854e+07,...,2.499319e+07,True,False,None,True,False,None,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,6.078571e+08,2.442760e+08,3.635811e+08,0.401864,2.407451e+07,...,1.602517e+07,True,False,None,True,False,None,True,False,None
6396,2024-03-31,季报,2024-04-30,非标准无保留意见,False,6.964087e+08,3.119972e+08,3.844115e+08,0.448009,2.826385e+07,...,1.454014e+07,True,True,True,True,False,None,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.592984e+08,4.373654e+08,4.219330e+08,0.508980,3.399481e+07,...,1.482556e+07,True,True,True,True,False,None,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.401049e+08,5.266185e+08,4.134865e+08,0.560170,3.892565e+07,...,1.857244e+07,True,True,True,True,False,None,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,1.153727e+09,7.256438e+08,4.280837e+08,0.628956,4.518259e+07,...,2.011653e+07,True,True,True,True,False,None,True,False,None

---

# Law Article 18

## MEU_18_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 披露高送转方案且最近两年同期净利润持续增长 |
| constraint | 每股送转股比例不得高于上市公司最近两年同期净利润的复合增长率 |
| contextual_info | nan |
| note | nan |
| relation | refer_to |
| target | MEU_31_2;MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2176 |
| completion_tokens | 10773 |

### 代码实现

In [27]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_10.csv')
date_columns = ["财务数据日期", "公告日期", "日期"]
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [28]:
import pandas as pd
import numpy as np

def check_meu_18_1(df):
    # 创建副本避免修改原数据
    df = df.copy()
    
    # 初始化合规标记列（保持constraint初始值为None）
    df['meu_18_1_subject'] = True
    df['meu_18_1_condition'] = False
    df['meu_18_1_constraint'] = None  # 初始设为None

    # 生成基础时间信息
    df['current_year'] = df['财务数据日期'].dt.year
    df['month'] = df['财务数据日期'].dt.month

    # 过滤有效报告期（年报12月/中期6月）
    valid_month_mask = df['month'].isin([6, 12])
    df['is_valid_report'] = valid_month_mask

    # 准备历史数据
    history_df = df[['公司简称', 'current_year', 'month', '归属于上市公司股东的净利润']].copy()
    
    # 合并N-1年数据
    df['match_year'] = df['current_year'] - 1
    df = df.merge(
        history_df.rename(columns={'归属于上市公司股东的净利润': 'prev_net', 'current_year': 'hist_year'}),
        left_on=['公司简称', 'match_year', 'month'],
        right_on=['公司简称', 'hist_year', 'month'],
        how='left'
    ).drop(columns=['hist_year'])

    # 合并N-2年数据
    df['match_year'] = df['current_year'] - 2
    df = df.merge(
        history_df.rename(columns={'归属于上市公司股东的净利润': 'prev_prev_net', 'current_year': 'hist_year'}),
        left_on=['公司简称', 'match_year', 'month'],
        right_on=['公司简称', 'hist_year', 'month'],
        how='left'
    ).drop(columns=['hist_year'])

    # 条件1: 高送转判断
    df['送转合计'] = df['送股比例'] + df['转增比例']
    high_send = (df['送转合计'] >= 5) & df['是否进行权益分派']

    # 条件2: 净利润增长（仅在有效报告期判断）
    growth_condition = (
        (df['归属于上市公司股东的净利润'] > df['prev_net']) & 
        (df['prev_net'] > df['prev_prev_net'])
    )
    df['meu_18_1_condition'] = (high_send & growth_condition).where(valid_month_mask, False)

    # 约束条件计算（核心修改点）
    # 仅对有效报告期计算增长率
    denominator = df['prev_prev_net'].abs().replace(0, np.nan)
    ratio = df['归属于上市公司股东的净利润'] / denominator
    compound_growth = np.sqrt(ratio.where(ratio > 0)) - 1
    
    send_ratio = df['送转合计'] / 10
    
    # 分两步设置约束条件
    valid_constraint = (send_ratio <= compound_growth)  # 原始条件判断
    df['meu_18_1_constraint'] = (
        (df['meu_18_1_condition'] & valid_constraint)  # 有效报告期计算结果
        .where(valid_month_mask, None)  # 非有效报告期设为None
        .replace({np.nan: None})  # 将NaN转为None
    )

    # # 清理中间列
    # df.drop(columns=[
    #     'current_year', 'month', 'match_year', 
    #     'prev_net', 'prev_prev_net', '送转合计', 'is_valid_report'
    # ], inplace=True, errors='ignore')
    
    return df

In [29]:
df = check_meu_18_1(df)
df.to_csv('temp.csv', encoding='utf-8-sig', index=False)

---

## MEU_18_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 披露高送转方案且在报告期内实施再融资、并购重组等导致净资产有较大变化 |
| constraint | 每股送转股比例不得高于上市公司报告期末净资产较之于期初净资产的增长率 |
| contextual_info | nan |
| note | nan |
| relation | refer_to |
| target | MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2110 |
| completion_tokens | 7418 |

### 代码实现

In [30]:
import pandas as pd

def check_meu_18_2(df):
    '''
    合规性检查函数：MEU_18_2
    subject: 上市公司
    condition: 披露高送转方案且在报告期内实施再融资、并购重组等导致净资产有较大变化
    constraint: 每股送转股比例不得高于上市公司报告期末净资产较之于期初净资产的增长率
    '''
    # 初始化标记列
    df['meu_18_2_subject'] = True  # 所有行均为上市公司
    df['meu_18_2_condition'] = False
    df['meu_18_2_constraint'] = None

    # 条件验证：高送转方案 (每10股送转合计≥5股)
    high_send_condition = (df['送股比例'] + df['转增比例']) >= 5

    # 条件验证：再融资或并购导致净资产有较大变化
    has_refinance = df['再融资或并购导致净资产有较大变化']

    # 合并条件验证结果
    df['meu_18_2_condition'] = high_send_condition & has_refinance

    # 约束验证：计算实际净资产增长率
    df_sorted = df.sort_values(['公司简称', '财务数据日期'])
    df_sorted['prev_净资产'] = df_sorted.groupby('公司简称')['净资产'].shift(1)
    df_sorted['实际净资产增长率'] = (df_sorted['净资产'] - df_sorted['prev_净资产']) / df_sorted['prev_净资产']
    df = df_sorted.reset_index(drop=True)

    # 计算送转股比例约束
    total_send_ratio = (df['送股比例'] + df['转增比例']) / 10
    df['meu_18_2_constraint'] = total_send_ratio <= df['实际净资产增长率']

    # 清理临时列
    df.drop(['prev_净资产', '实际净资产增长率'], axis=1, errors='ignore')
    
    return df

In [31]:
df = check_meu_18_2(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,is_valid_report,match_year,prev_net,prev_prev_net,送转合计,meu_18_2_subject,meu_18_2_condition,meu_18_2_constraint,prev_净资产,实际净资产增长率
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.384595e+08,5.967386e+07,1.787856e+08,0.250247,1.534606e+07,...,False,2015,NaN,NaN,0,True,False,False,NaN,NaN
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.123215e+08,4.807545e+07,1.642460e+08,0.226428,1.422379e+07,...,True,2015,NaN,NaN,0,True,False,False,1.787856e+08,-0.081324
2,2017-09-30,季报,2017-10-27,无保留意见,False,2.217586e+08,4.934872e+07,1.724099e+08,0.222534,1.443740e+07,...,False,2015,NaN,NaN,0,True,False,True,1.642460e+08,0.049705
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.333176e+08,5.725981e+07,1.760578e+08,0.245416,1.669366e+07,...,True,2015,NaN,NaN,0,True,False,True,1.724099e+08,0.021158
4,2018-03-31,季报,2018-04-30,无保留意见,False,2.723056e+08,6.839593e+07,2.039096e+08,0.251173,1.812854e+07,...,False,2016,-7.931183e+06,NaN,0,True,False,True,1.760578e+08,0.158197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,6.078571e+08,2.442760e+08,3.635811e+08,0.401864,2.407451e+07,...,True,2021,-6.052195e+06,2.022819e+07,0,True,False,False,3.676487e+08,-0.011064
6396,2024-03-31,季报,2024-04-30,非标准无保留意见,False,6.964087e+08,3.119972e+08,3.844115e+08,0.448009,2.826385e+07,...,False,2022,-1.045176e+05,9.931653e+06,0,True,False,True,3.635811e+08,0.057292
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.592984e+08,4.373654e+08,4.219330e+08,0.508980,3.399481e+07,...,True,2022,8.090967e+06,3.104910e+06,0,True,False,True,3.844115e+08,0.097607
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.401049e+08,5.266185e+08,4.134865e+08,0.560170,3.892565e+07,...,False,2022,-4.491879e+06,4.353195e+05,2,True,False,False,4.219330e+08,-0.020019
6399,2024-12-31,年报,2025-03-30,无保留意见,False,1.153727e+09,7.256438e+08,4.280837e+08,0.628956,4.518259e+07,...,True,2022,-1.702619e+07,-6.052195e+06,0,True,False,True,4.134865e+08,0.035303

---

## MEU_18_3


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 披露高送转方案且最近两年净利润持续增长且最近三年每股收益均不低于1元且上市公司认为确有必要且依据年度财务报表进行高送转 |
| constraint | 应当充分披露高送转的主要考虑及其合理性且送转股后每股收益不低于0.5元 |
| contextual_info | nan |
| note | "每股收益"简化为采用"每股净利润" |
| relation | refer_to |
| target | MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2136 |
| completion_tokens | 7837 |

In [32]:
300*0.7

210.0

In [33]:
300*0.15

45.0

### 代码实现

In [34]:
# 读取模拟数据
import pandas as pd
df = pd.read_csv('data_simulation/data_generated/data_simulate_10.csv')
date_columns = ["财务数据日期", "公告日期", "日期"]
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [ ]:
import pandas as pd
from utils.tool_for_agents import llm_content_check

def check_meu_18_3(df):
    '''
    验证上市公司高送转方案的合规性：
    "subject": "上市公司",
    "condition": "披露高送转方案且最近两年净利润持续增长且最近三年每股收益均不低于1元且上市公司认为确有必要且依据年度财务报表进行高送转",
    "constraint": "应当充分披露高送转的主要考虑及其合理性且送转股后每股收益不低于0.5元"
    '''
    
    # 初始化合规标记列
    df['meu_18_3_subject'] = True  # 所有记录主体均为上市公司
    df['meu_18_3_condition'] = False
    df['meu_18_3_constraint'] = None

    # 转换财务数据日期格式
    df['财务数据日期'] = pd.to_datetime(df['财务数据日期'])
    
    # ======================
    # 预处理：仅在年报数据上计算历史指标
    # ======================
    
    # 筛选并排序年报数据
    annual_mask = df['财务数据日期'].dt.month == 12
    annual_df = df[annual_mask].sort_values(['公司简称', '财务数据日期']).copy()
    
    # 在年报数据中计算历史指标（按公司分组后shift）
    annual_df['prev_year_net'] = annual_df.groupby('公司简称')['归属于上市公司股东的净利润'].shift(1)
    annual_df['prev_prev_year_net'] = annual_df.groupby('公司简称')['归属于上市公司股东的净利润'].shift(2)
    annual_df['eps_prev1'] = annual_df.groupby('公司简称')['每股净利润'].shift(1)
    annual_df['eps_prev2'] = annual_df.groupby('公司简称')['每股净利润'].shift(2)
    
    # 将计算结果合并回原始数据
    merge_cols = ['公司简称', '财务数据日期', 'prev_year_net', 'prev_prev_year_net', 'eps_prev1', 'eps_prev2']
    df = df.merge(annual_df[merge_cols], on=['公司简称', '财务数据日期'], how='left')
    
    # ======================
    # 条件验证部分
    # ======================
    
    # 1. 年度报表标识
    is_annual_report = annual_mask
    
    # 2. 高送转方案验证（每10股送转≥5股）
    sz_ratio = df['送股比例'] + df['转增比例']
    high_sz = sz_ratio >= 5
    
    # 3. 净利润持续增长验证（基于年报数据计算的历史指标）
    net_growth = (df['归属于上市公司股东的净利润'] > df['prev_year_net']) & (df['prev_year_net'] > df['prev_prev_year_net'])
    
    # 4. 每股收益验证（三年EPS≥1）
    eps_valid = (df['每股净利润'] >= 1) & (df['eps_prev1'] >= 1) & (df['eps_prev2'] >= 1)
    
    # 5. 必要性验证（LLM内容检查）
    necessity_check = df['权益分派方案文本'].apply(
        lambda x: llm_content_check(x, "上市公司认为确有必要实施高送转") if pd.notnull(x) else False
    )
    
    # 6. 权益分派执行标记
    is_distributed = df['是否进行权益分派']
    
    # 综合条件判断（仅年报记录可能满足）
    condition_met = (
        is_annual_report &
        high_sz &
        net_growth.fillna(False) &  # 非年报或历史数据不足时为False
        eps_valid.fillna(False) &
        necessity_check &
        is_distributed
    )
    df.loc[condition_met, 'meu_18_3_condition'] = True
    
    # ======================
    # 约束验证部分
    # ======================
    
    # 1. 合理性披露检查
    disclosure_check = df['权益分派方案文本'].apply(
        lambda x: llm_content_check(x, "高送转的主要考虑及其合理性") if pd.notnull(x) else False
    )
    
    # 2. 送转后EPS计算（仅对高送转记录生效）
    post_eps = df['每股净利润'] * (10 / (10 + df['送股比例'] + df['转增比例']))
    eps_constraint = post_eps >= 0.5
    
    # 综合约束判断
    constraint_met = disclosure_check & eps_constraint
    df.loc[constraint_met, 'meu_18_3_constraint'] = True
    df.loc[~constraint_met, 'meu_18_3_constraint'] = False
    
    # 清理中间列
    df.drop(columns=['prev_year_net', 'prev_prev_year_net', 'eps_prev1', 'eps_prev2'], 
            inplace=True, errors='ignore')
    
    return df

In [36]:
df = check_meu_18_3(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,相关股东后三个月存在减持计划,现金分红金额,送股比例,转增比例,是否进行权益分派,权益分派方案文本,公司简称,meu_18_3_subject,meu_18_3_condition,meu_18_3_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,True
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,None
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,False,0.0,0,0,False,[],蔚珵食品,True,False,None
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,False,0.0,1,0,True,['留存未分配利润的预计用途以及收益情况'],蔚珵食品,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,False,None

In [37]:
df['meu_18_3_condition'].sum()

np.int64(0)

In [38]:
df[df['meu_18_3_condition']==True]

Empty DataFrame
Columns: [财务数据日期, 公告类型, 公告日期, 审计意见, 再融资或并购导致净资产有较大变化, 总资产, 总负债, 净资产, 资产负债率, 交易性金融资产, 衍生金融资产, 债权投资, 其他债权投资, 其他权益工具投资, 其他非流动金融资产, 其他流动资产, 金融资产总额, 总股本, 每股净资产, 合并报表未分配利润, 母公司报表未分配利润, 营业收入, 归属于上市公司股东的净利润, 每股净利润, 母公司报表净利润, 经营活动现金流量净额, 投资活动现金流量净额, 筹资活动现金流量净额, 现金及现金等价物净增加额, 净资产增长率, 净利润增长率, 资产负债率变化, 金融资产增长率, 上市日期, 日期, 是否实施现金分红, 是否实施股票股利, 是否公积金转增股本, 相关股东前三个月内存在减持情形, 相关股东后三个月存在减持计划, 现金分红金额, 送股比例, 转增比例, 是否进行权益分派, 权益分派方案文本, 公司简称, meu_18_3_subject, meu_18_3_condition, meu_18_3_constraint]
Index: []

[0 rows x 49 columns]

---

# Law Article 19

## MEU_19_1


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 报告期尚未产生收入 |
| constraint | 不得披露高送转方案 |
| contextual_info | nan |
| note | nan |
| relation | refer_to |
| target | MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2083 |
| completion_tokens | 4630 |

### 代码实现

In [39]:
import pandas as pd

def check_meu_19_1(df):
    '''
    检查MEU_19_1合规性：
    - subject: 上市公司（所有记录默认满足）
    - condition: 报告期尚未产生收入（使用营业收入<=0判断）
    - constraint: 未披露高送转方案（送转合计<5股）
    '''

    # 初始化标记列
    df['meu_19_1_subject'] = True  # 所有记录均为上市公司
    df['meu_19_1_condition'] = False
    df['meu_19_1_constraint'] = None

    # 标记condition：报告期尚未产生收入（使用营业收入<=0判断）
    # 注意：法律条文中的"产生收入"应指营业收入
    df['meu_19_1_condition'] = df['营业收入'] <= 0

    # 标记constraint：未披露高送转方案
    # 计算送转合计（处理空值为0）
    total_distribution = df['送股比例'].fillna(0) + df['转增比例'].fillna(0)
    # 判断是否达到高送转标准（每10股送转≥5股）
    is_high_distribution = total_distribution >= 5
    # 约束成立条件：未进行权益分派 或 分派但未达高送转标准
    df['meu_19_1_constraint'] = ~(df['是否进行权益分派'] & is_high_distribution)

    return df

In [40]:
df = check_meu_19_1(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,转增比例,是否进行权益分派,权益分派方案文本,公司简称,meu_18_3_subject,meu_18_3_condition,meu_18_3_constraint,meu_19_1_subject,meu_19_1_condition,meu_19_1_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,0,False,[],曦祺电力,True,False,None,True,False,True
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,0,False,[],曦祺电力,True,False,None,True,False,True
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,0,False,[],曦祺电力,True,False,True,True,False,True
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,0,False,[],曦祺电力,True,False,None,True,False,True
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,0,False,[],曦祺电力,True,False,None,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,0,False,[],蔚珵食品,True,False,None,True,False,True
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,0,False,[],蔚珵食品,True,False,None,True,False,True
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,0,False,[],蔚珵食品,True,False,None,True,False,True
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,0,True,['留存未分配利润的预计用途以及收益情况'],蔚珵食品,True,False,None,True,False,True
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,0,False,[],蔚珵食品,True,False,None,True,False,True

---

## MEU_19_2


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 净利润为负 |
| constraint | 不得披露高送转方案 |
| contextual_info | nan |
| note | nan |
| relation | refer_to |
| target | MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2081 |
| completion_tokens | 4348 |

### 代码实现

In [41]:
import pandas as pd

def check_meu_19_2(df):
    '''
    检查MEU_19_2合规性：
    subject: 上市公司
    condition: 净利润为负
    constraint: 不得披露高送转方案
    contextual_info: 高送转定义参考MEU_17_1（每10股合计送转≥5股）
    '''
    # 初始化标记列
    df['meu_19_2_subject'] = True  # 数据主体均为上市公司
    df['meu_19_2_condition'] = False
    df['meu_19_2_constraint'] = None

    # 标记条件满足情况 --------------------------------------------------------
    # 1.标记subject（所有行已默认True）
    
    # 2.标记condition（净利润为负）
    df['meu_19_2_condition'] = df['归属于上市公司股东的净利润'] < 0
    
    # 3.标记constraint（未披露高送转）
    # 计算高送转条件：进行权益分派且送转合计≥5股/10股
    high_send_condition = (
        df['是否进行权益分派'] & 
        ((df['送股比例'] + df['转增比例']) >= 5)
    )
    df['meu_19_2_constraint'] = ~high_send_condition  # 约束满足=未实施高送转

    return df

In [42]:
df = check_meu_19_2(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,公司简称,meu_18_3_subject,meu_18_3_condition,meu_18_3_constraint,meu_19_1_subject,meu_19_1_condition,meu_19_1_constraint,meu_19_2_subject,meu_19_2_condition,meu_19_2_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,曦祺电力,True,False,None,True,False,True,True,True,True
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,曦祺电力,True,False,None,True,False,True,True,False,True
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,曦祺电力,True,False,True,True,False,True,True,False,True
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,曦祺电力,True,False,None,True,False,True,True,False,True
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,曦祺电力,True,False,None,True,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,蔚珵食品,True,False,None,True,False,True,True,True,True
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,蔚珵食品,True,False,None,True,False,True,True,True,True
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,蔚珵食品,True,False,None,True,False,True,True,False,True
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,蔚珵食品,True,False,None,True,False,True,True,False,True
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,蔚珵食品,True,False,None,True,False,True,True,False,True

---

## MEU_19_3


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 净利润同比下降50%以上 |
| constraint | 不得披露高送转方案 |
| contextual_info | nan |
| note | nan |
| relation | refer_to |
| target | MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2083 |
| completion_tokens | 3810 |

### 代码实现

In [43]:
import pandas as pd

def check_meu_19_3(df):
    '''
    验证MEU_19_3合规性:
    - subject: 上市公司（所有记录默认满足）
    - condition: 净利润同比下降50%以上（净利润增长率<=-0.5）
    - constraint: 不得披露高送转方案（送股+转增<5股）
    '''

    # 初始化标记列
    df['meu_19_3_subject'] = True  # 所有记录主体均为上市公司
    df['meu_19_3_condition'] = False
    df['meu_19_3_constraint'] = None

    # 标记条件满足情况
    # 1. 验证净利润同比下降50%以上（单季度同比）
    df['meu_19_3_condition'] = df['净利润增长率'] <= -0.5

    # 2. 验证高送转约束（仅当主体和条件同时满足时检查）
    # 计算送转总和（处理可能的NaN值）
    send_ratio = df['送股比例'].fillna(0)
    transfer_ratio = df['转增比例'].fillna(0)
    high_send = (send_ratio + transfer_ratio) >= 5

    # 确定需要检查约束的有效范围
    mask = df['meu_19_3_subject'] & df['meu_19_3_condition']
    # 在约束范围内标记违规（存在高送转）
    df.loc[mask, 'meu_19_3_constraint'] = ~high_send[mask]

    return df

In [44]:
df = check_meu_19_3(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,meu_18_3_constraint,meu_19_1_subject,meu_19_1_condition,meu_19_1_constraint,meu_19_2_subject,meu_19_2_condition,meu_19_2_constraint,meu_19_3_subject,meu_19_3_condition,meu_19_3_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,None,True,False,True,True,True,True,True,False,None
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,None,True,False,True,True,False,True,True,False,None
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,True,True,False,True,True,False,True,True,False,None
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,None,True,False,True,True,False,True,True,False,None
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,None,True,False,True,True,False,True,True,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,None,True,False,True,True,True,True,True,False,None
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,None,True,False,True,True,True,True,True,False,None
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,None,True,False,True,True,False,True,True,False,None
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,None,True,False,True,True,False,True,True,False,None
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,None,True,False,True,True,False,True,True,False,None

---

## MEU_19_4


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 送转股后每股收益低于0.2元 |
| constraint | 不得披露高送转方案 |
| contextual_info | nan |
| note | "每股收益"简化为采用"每股净利润" |
| relation | refer_to |
| target | MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2098 |
| completion_tokens | 7258 |

### 代码实现

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('data_simulation/data_generated/data_simulate_10.csv')
date_columns = ["财务数据日期", "公告日期", "日期", "上市日期"]
for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [2]:
import pandas as pd

def check_meu_19_4(df):
    '''
    检查上市公司在送转股后每股收益低于0.2元时是否违规披露高送转方案。
    MEU内容:
    - subject: 上市公司
    - condition: 送转股后每股收益低于0.2元
    - constraint: 不得披露高送转方案
    '''

    # 初始化标记列
    df['meu_19_4_subject'] = True  # 所有行主体均为上市公司
    df['meu_19_4_condition'] = False
    df['meu_19_4_constraint'] = None

    # 计算高送转条件（每10股送转合计≥5股）
    total_sz_ratio = df['送股比例'] + df['转增比例']
    is_high_sz = total_sz_ratio >= 5

    # 计算送转后每股收益（考虑股本扩张效应）
    df['post_eps'] = df['每股净利润'] * 10 / (10 + total_sz_ratio)

    # 条件验证：实际实施高送转且送转后EPS<0.2
    valid_condition = (
        df['是否进行权益分派'] & 
        is_high_sz & 
        (df['post_eps'] < 0.2)
    )
    df['meu_19_4_condition'] = valid_condition

    # 约束验证：当条件成立时不得实施高送转
    df['meu_19_4_constraint'] = ~is_high_sz

    # 清理中间列
    df.drop(columns=['post_eps'], inplace=True, errors='ignore')

    return df

In [3]:
df = check_meu_19_4(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,相关股东后三个月存在减持计划,现金分红金额,送股比例,转增比例,是否进行权益分派,权益分派方案文本,公司简称,meu_19_4_subject,meu_19_4_condition,meu_19_4_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,True
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,True
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,True
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,True
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,False,0.0,0,0,False,[],曦祺电力,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,False,0.0,0,0,False,[],蔚珵食品,True,False,True
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,False,True
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,False,True
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,False,0.0,1,0,True,['留存未分配利润的预计用途以及收益情况'],蔚珵食品,True,False,True
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,False,0.0,0,0,False,[],蔚珵食品,True,False,True

---

## MEU_19_5


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 相关股东在前三个月存在减持情形 |
| constraint | 不得披露高送转方案 |
| contextual_info | 相关股东指公司的提议股东和控股股东及其一致行动人、董事、监事及高级管理人员 |
| note | nan |
| relation | refer_to |
| target | MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2105 |
| completion_tokens | 2801 |

### 代码实现

In [47]:
import pandas as pd

def check_meu_19_5(df):
    '''
    验证MEU_19_5合规性:
    - subject: 上市公司
    - condition: 相关股东前三个月存在减持情形
    - constraint: 不得披露高送转方案
    '''

    # 初始化标记列
    df['meu_19_5_subject'] = True  # 所有记录主体均为上市公司
    df['meu_19_5_condition'] = df['相关股东前三个月内存在减持情形']
    df['meu_19_5_constraint'] = None

    # 计算高送转方案指标（每10股合计送转≥5股）
    total_distribution = df['送股比例'] + df['转增比例']
    is_high_send = total_distribution >= 5
    
    # 判断是否实际披露高送转（需同时满足权益分派和送转比例条件）
    has_high_send_plan = df['是否进行权益分派'] & is_high_send
    df['meu_19_5_constraint'] = ~has_high_send_plan


    return df

In [48]:
df = check_meu_19_5(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,meu_19_2_constraint,meu_19_3_subject,meu_19_3_condition,meu_19_3_constraint,meu_19_4_subject,meu_19_4_condition,meu_19_4_constraint,meu_19_5_subject,meu_19_5_condition,meu_19_5_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,True,True,False,None,True,False,True,True,False,True
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,True,True,False,None,True,False,True,True,False,True
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,True,True,False,None,True,False,True,True,False,True
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,True,True,False,None,True,False,True,True,False,True
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,True,True,False,None,True,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,True,True,False,None,True,False,True,True,True,True
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,True,True,False,None,True,False,True,True,True,True
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,True,True,False,None,True,False,True,True,False,True
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,True,True,False,None,True,False,True,True,False,True
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,True,True,False,None,True,False,True,True,False,True

---

## MEU_19_6


| 字段 | 内容 |
|------|------|
| subject | 上市公司 |
| condition | 相关股东在后三个月存在减持计划 |
| constraint | 不得披露高送转方案 |
| contextual_info | 相关股东指公司的提议股东和控股股东及其一致行动人、董事、监事及高级管理人员 |
| note | nan |
| relation | refer_to |
| target | MEU_17_1 |
| type | 实际执行单元 |
| comments | nan |
| prompt_tokens | 2105 |
| completion_tokens | 5459 |

### 代码实现

In [ ]:
import pandas as pd

def check_meu_19_6(df):
    '''
    验证上市公司在相关股东存在未来三个月减持计划时是否违规披露高送转方案
    MEU_19_6参数:
    - subject: 上市公司
    - condition: 相关股东在后三个月存在减持计划
    - constraint: 不得披露高送转方案
    - contextual_info: 相关股东定义及高送转标准参考
    '''

    # 初始化合规标记列
    df['meu_19_6_subject'] = True  # 数据源默认均为上市公司
    df['meu_19_6_condition'] = False
    df['meu_19_6_constraint'] = None

    # 1. 标记valid的subject（所有行默认满足）
    # 根据数据特性，假设所有记录主体均为上市公司

    # 2. 标记valid的condition
    df['meu_19_6_condition'] = df['相关股东后三个月存在减持计划']

    # 3. 标记valid的constraint
    # 计算高送转标准（每10股合计≥5股）
    high_song_zhuan = (df['送股比例'] + df['转增比例']) >= 5
    # 结合权益分派实施状态
    high_song_zhuan = df['是否进行权益分派'] & high_song_zhuan
    # 约束有效性判断：不得存在高送转
    df['meu_19_6_constraint'] = ~high_song_zhuan

    return df

In [50]:
df = check_meu_19_6(df)
df

,财务数据日期,公告类型,公告日期,审计意见,再融资或并购导致净资产有较大变化,总资产,总负债,净资产,资产负债率,交易性金融资产,...,meu_19_3_constraint,meu_19_4_subject,meu_19_4_condition,meu_19_4_constraint,meu_19_5_subject,meu_19_5_condition,meu_19_5_constraint,meu_19_6_subject,meu_19_6_condition,meu_19_6_constraint
0,2017-03-31,季报,2017-04-30,无保留意见,False,2.842522e+08,1.130877e+08,1.711645e+08,0.397843,8.098972e+02,...,None,True,False,True,True,False,True,True,False,True
1,2017-06-30,半年报,2017-08-27,无保留意见,False,2.966845e+08,1.135991e+08,1.830854e+08,0.382895,7.693282e+02,...,None,True,False,True,True,False,True,True,False,True
2,2017-09-30,季报,2017-10-27,无保留意见,False,3.027739e+08,1.224971e+08,1.802768e+08,0.404583,8.354786e+02,...,None,True,False,True,True,False,True,True,False,True
3,2017-12-31,年报,2018-03-30,无保留意见,False,2.925768e+08,1.203038e+08,1.722730e+08,0.411187,8.239055e+02,...,None,True,False,True,True,False,True,True,False,True
4,2018-03-31,季报,2018-04-30,无保留意见,False,3.380136e+08,1.256449e+08,2.123687e+08,0.371715,9.071208e+02,...,None,True,False,True,True,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,2023-12-31,年报,2024-03-30,无保留意见,False,7.347533e+08,4.043164e+08,3.304369e+08,0.550275,8.798285e+07,...,None,True,False,True,True,True,True,True,False,True
6396,2024-03-31,季报,2024-04-30,无保留意见,False,8.080286e+08,4.626518e+08,3.453768e+08,0.572569,1.027686e+08,...,None,True,False,True,True,True,True,True,False,True
6397,2024-06-30,半年报,2024-08-27,无保留意见,False,8.992892e+08,5.516279e+08,3.476613e+08,0.613404,1.098830e+08,...,None,True,False,True,True,False,True,True,False,True
6398,2024-09-30,季报,2024-10-27,无保留意见,False,9.021211e+08,5.477615e+08,3.543596e+08,0.607193,1.049263e+08,...,None,True,False,True,True,False,True,True,False,True
6399,2024-12-31,年报,2025-03-30,无保留意见,False,8.910095e+08,5.021467e+08,3.888628e+08,0.563571,1.082111e+08,...,None,True,False,True,True,False,True,True,False,True

---